# Read the file

In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.backends.backend_pdf import PdfPages
import seaborn as sns
matplotlib.style.use('ggplot')
%matplotlib inline

In [2]:
%time df_all= pd.read_csv('dublin_2012_11_distance.csv',dtype={ 'Journey_Pattern_ID': object})
#df_all.dtypes

<string>:2: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.

CPU times: user 34.8 s, sys: 12.9 s, total: 47.8 s
Wall time: 55.6 s

In [3]:
df_all.head()

,Timestamp,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Lon_WGS84,Lat_WGS84,Stop_ID,At_Stop,First_Stop,Last_Stop,...,Trip_Time,datetime,HourOfDay,day_of_week,midweek,time_bin,cloud,rain,temp,wind
0,1352204113,00010001,2012-11-06,5427,-6.262000,53.391182,226,1,226,380,...,0,2012-11-06 12:15:13,12,Tuesday,0,am,6.88,0.0,7.55,16.25
1,1352204473,00010001,2012-11-06,5427,-6.262341,53.391186,226,0,226,380,...,360,2012-11-06 12:21:13,12,Tuesday,0,am,6.88,0.0,7.55,16.25
2,1352204510,00010001,2012-11-06,5427,-6.259799,53.391804,228,1,226,380,...,397,2012-11-06 12:21:50,12,Tuesday,0,am,6.88,0.0,7.55,16.25
3,1352204531,00010001,2012-11-06,5427,-6.259056,53.391758,228,0,226,380,...,418,2012-11-06 12:22:11,12,Tuesday,0,am,6.88,0.0,7.55,16.25
4,1352204553,00010001,2012-11-06,5427,-6.256530,53.391335,229,1,226,380,...,440,2012-11-06 12:22:33,12,Tuesday,0,am,6.88,0.0,7.55,16.25

In [4]:
df=df_all

In [5]:
df=df.drop(df.index[df['At_Stop']==0])

In [6]:
zscore=lambda x: x.mean()
df['Distance']=df.groupby(['Journey_Pattern_ID','Stop_ID'])['Distance'].transform(zscore)

In [7]:
df[['Journey_Pattern_ID','Stop_ID']]

        Journey_Pattern_ID  Stop_ID
0                 00010001      226
2                 00010001      228
4                 00010001      229
11                00010001      213
17                00010001       45
19                00010001       46
21                00010001       47
24                00010001       49
27                00010001       51
29                00010001       52
31                00010001      265
33                00010001      271
35                00010001      340
38                00010001      351
40                00010001      352
45                00010001      356
47                00010001      357
49                00010001      390
51                00010001      372
54                00010001      374
61                00010001      380
64                00010001      229
66                00010001      227
69                00010001      231
71                00010001     1641
74                00010001      213
81                00010001       46
84                00010001       48
89                00010001       52
91                00010001      265
...                    ...      ...
2209215           084A1002     3084
2209224           084A1002      478
2209225           084A1002     4168
2209228           084A1002     4153
2209233           084A1002     4202
2209239           084A1002     3141
2209242           084A1002     3143
2209250           084A1002     3153
2209267           084A1002     3084
2209274           084A1002      478
2209308           OL77X101     4714
2209311           OL77X101     2427
2209313           OL77X101     2430
2209315           OL77X101     2371
2209318           OL77X101     2373
2209326           OL77X101     4714
2209330           OL77X101     2430
2209332           OL77X101     2371
2209338           OL77X101     1424
2209343           OL77X101     4714
2209348           OL77X101     2371
2209357           OL77X101     2190
2209358           OL77X101     4714
2209363           OL77X101     2371
2209369           OL77X101     1424
2209375           PP071001     3224
2209390           PP071001      476
2209394           PP071001      487
2209399           PP071001      279
2209401           PP071001     4962

[618829 rows x 2 columns]

In [8]:
df.head()

,Timestamp,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Lon_WGS84,Lat_WGS84,Stop_ID,At_Stop,First_Stop,Last_Stop,...,Trip_Time,datetime,HourOfDay,day_of_week,midweek,time_bin,cloud,rain,temp,wind
0,1352204113,00010001,2012-11-06,5427,-6.262000,53.391182,226,1,226,380,...,0,2012-11-06 12:15:13,12,Tuesday,0,am,6.88,0.0,7.55,16.25
2,1352204510,00010001,2012-11-06,5427,-6.259799,53.391804,228,1,226,380,...,397,2012-11-06 12:21:50,12,Tuesday,0,am,6.88,0.0,7.55,16.25
4,1352204553,00010001,2012-11-06,5427,-6.256530,53.391335,229,1,226,380,...,440,2012-11-06 12:22:33,12,Tuesday,0,am,6.88,0.0,7.55,16.25
11,1352204851,00010001,2012-11-06,5427,-6.245068,53.381519,213,1,226,380,...,738,2012-11-06 12:27:31,12,Tuesday,0,am,6.88,0.0,7.55,16.25
17,1352205072,00010001,2012-11-06,5427,-6.254246,53.369949,45,1,226,380,...,959,2012-11-06 12:31:12,12,Tuesday,0,am,6.88,0.0,7.55,16.25

In [9]:
df_stops=df[['Journey_Pattern_ID','Stop_ID','Distance']]

In [10]:
df_stops=df_stops.drop_duplicates()

In [51]:
df_stops.drop(df_stops.index[df_stops['Journey_Pattern_ID']=='OL77X101'],inplace=True)
df_stops.drop(df_stops.index[df_stops['Journey_Pattern_ID']=='PP071001'],inplace=True)
# Drop by the value of one feature 
#df=df.drop(df.index[df['Journey_Pattern_ID'].isnull()])

In [11]:
df_stops['Journey_Pattern_ID']=df_stops['Journey_Pattern_ID'].astype(str)

In [42]:
df_stops['Line_ID']= df_stops['Journey_Pattern_ID'].apply(lambda x:x[1:4:])
df_stops['Direction']= df_stops['Journey_Pattern_ID'].apply(lambda x:x[5:6])

In [43]:
df_stops.shape

(17259, 5)

In [44]:
df_stops.dtypes

Journey_Pattern_ID     object
Stop_ID                 int64
Distance              float64
Line_ID                object
Direction              object
dtype: object

In [52]:
df_stops

        Journey_Pattern_ID  Stop_ID      Distance Line_ID Direction
0                 00010001      226      0.000000     001         0
2                 00010001      228    232.285714     001         0
4                 00010001      229    469.898305     001         0
11                00010001      213   2352.663265     001         0
17                00010001       45   3823.538462     001         0
19                00010001       46   4072.135593     001         0
21                00010001       47   4454.492754     001         0
24                00010001       49   4980.031250     001         0
27                00010001       51   5240.177419     001         0
29                00010001       52   5418.525424     001         0
31                00010001      265   6306.583333     001         0
33                00010001      271   6873.462963     001         0
35                00010001      340   7288.761006     001         0
38                00010001      351   8095.847059     001         0
40                00010001      352   8316.946237     001         0
45                00010001      356   9357.233333     001         0
47                00010001      357   9744.990991     001         0
49                00010001      390   9921.701754     001         0
51                00010001      372  10286.731343     001         0
54                00010001      374  10580.400000     001         0
61                00010001      380  12329.214286     001         0
66                00010001      227    862.014925     001         0
69                00010001      231   1330.617978     001         0
71                00010001     1641   1807.100000     001         0
84                00010001       48   4678.266667     001         0
97                00010001      350   7759.078947     001         0
103               00010001      353   8504.924731     001         0
105               00010001      354   8700.347826     001         0
107               00010001      355   8980.616667     001         0
168               00010001      376  11326.900000     001         0
...                    ...      ...           ...     ...       ...
2208502           084A1001     3158  11375.666667     84A         0
2208510           084A1001     3080  13968.000000     84A         0
2208529           084A1001     3141   4606.000000     84A         0
2208567           084A1001     4205   3447.000000     84A         0
2208580           084A1001     3148   8591.000000     84A         0
2208603           084A1001     3079  13894.500000     84A         0
2208698           084A1001     4154   1243.000000     84A         0
2208816           084A1001     3151   9935.000000     84A         0
2209014           084A1002     4168      0.000000     84A         0
2209017           084A1002     4153   1218.400000     84A         0
2209019           084A1002     4154   1081.000000     84A         0
2209021           084A1002     4416   1393.000000     84A         0
2209023           084A1002     4201   1694.000000     84A         0
2209025           084A1002     4202   2557.000000     84A         0
2209030           084A1002     3140   4185.500000     84A         0
2209032           084A1002     3141   4770.750000     84A         0
2209053           084A1002     3164  13240.500000     84A         0
2209059           084A1002      473  15859.000000     84A         0
2209065           084A1002      478  17522.600000     84A         0
2209094           084A1002     3158  11426.000000     84A         0
2209098           084A1002     3161  12298.333333     84A         0
2209112           084A1002     4705  17054.000000     84A         0
2209157           084A1002     3084  14351.333333     84A         0
2209165           084A1002      475  15711.000000     84A         0
2209180           084A1002     4204   3049.000000     84A         0
2209192           084A1002     3149   8832.000000     84A         0
2209196           084A1002     3153   9894.000000     84A         0
2209198           084A1002     3152   9899.000000     84A         0
2209202           084A1002     3156  10959.000000     84A         0
2209242           084A1002     3143   6018.000000     84A         0

[17247 rows x 5 columns]

In [39]:
df['Journey_Pattern_ID'].unique()

array(['00010001', '00010002', '00010003', '00011001', '00011002',
       '00040001', '00040002', '00041001', '00041002', '00070001',
       '00070002', '00070003', '00071001', '00071002', '00080001',
       '00081001', '00090001', '00090002', '00091001', '00091002',
       '00110001', '00110002', '00111001', '00111002', '00130001',
       '00130002', '00130003', '00130004', '00130005', '00130006',
       '00130007', '00130008', '00131001', '00131002', '00131003',
       '00131004', '00131005', '00131007', '00131008', '00131009',
       '00131010', '00131012', '00140001', '00141001', '00141003',
       '00150001', '00150002', '00151001', '00151002', '00160001',
       '00160002', '00160003', '00160004', '00161001', '00170001',
       '00170002', '00170003', '00170004', '00170005', '00171001',
       '00171002', '00171003', '00171004', '00180001', '00181001',
       '00181002', '00250001', '00251001', '00260001', '00261001',
       '00270001', '00270002', '00270003', '00271001', '00271002',
       '00271003', '00310001', '00310002', '00310003', '00311001',
       '00320001', '00321001', '00330002', '00331002', '00331004',
       '00370001', '00371001', '00371002', '00380001', '00380002',
       '00381001', '00381002', '00381003', '00390001', '00390002',
       '00391001', '00400001', '00400002', '00400003', '00400004',
       '00401001', '00401002', '00401003', '00410001', '00410003',
       '00410005', '00410006', '00410007', '00411001', '00411002',
       '00411003', '00411004', '00420001', '00420002', '00421001',
       '00421002', '00430001', '00430002', '00431001', '00431002',
       '00440001', '00440002', '00441001', '00441002', '00470001',
       '00470002', '00471001', '00471002', '00490001', '00491001',
       '00491002', '00530001', '00531001', '00590001', '00591001',
       '00610001', '00610002', '00611001', '00611002', '00630001',
       '00630002', '00630003', '00631001', '00631002', '00631003',
       '00631004', '00650003', '00651001', '00651003', '00660001',
       '00661001', '00670001', '00671001', '00680001', '00680002',
       '00680003', '00680004', '00681001', '00681002', '00681003',
       '00681004', '00681005', '00690001', '00691001', '00691002',
       '00700001', '00701001', '00750001', '00750002', '00751001',
       '00751002', '00751003', '00751004', '00760001', '00761001',
       '00790001', '00791001', '007B0001', '007B1001', '007D0001',
       '007D1001', '007D1002', '00830001', '00830003', '00830004',
       '00830006', '00831001', '00831003', '00831004', '00831006',
       '00840001', '00840003', '00840004', '00841001', '00841002',
       '00841004', '01020001', '01021001', '01021002', '01040001',
       '01041001', '01110001', '01111001', '01140001', '01141001',
       '01160001', '01161001', '01161002', '01181001', '01200001',
       '01200002', '01201001', '01201002', '01220001', '01220002',
       '01221001', '01221002', '01230001', '01230002', '01231001',
       '01231002', '01300001', '01301001', '01400001', '01400002',
       '01401001', '01401002', '01420001', '01421001', '01450001',
       '01450002', '01450003', '01450004', '01450005', '01451001',
       '01451002', '01451003', '01451004', '01451005', '01451006',
       '01451007', '01451008', '014C0001', '014C1001', '01500001',
       '01501001', '01510001', '01510002', '01511001', '01511002',
       '01511003', '015A0001', '015A0002', '015A1001', '015B0001',
       '015B0002', '015B0003', '015B1001', '015B1002', '01610001',
       '01611001', '01611002', '016C0001', '016C0002', '016C0003',
       '016C1001', '017A0001', '017A0002', '017A0004', '017A0005',
       '017A1001', '017A1002', '017A1003', '017A1004', '01840001',
       '01841001', '01850001', '01850002', '01850003', '01850004',
       '01850005', '01850006', '01851001', '01851002', '01851003',
       '01851004', '01851005', '01851006', '01851007', '01851008',
       '02200001', '02200002', '02201001', '02201002', '02360001',
       '02361001', '02380001', '02380002', '02381001', '02390001',
       '02390002', '02391001', '025A0001', '025A1001', '025B0001',
       '025B1001', '025X0001', '025X1001', '025X1002', '02700001',
       '02701001', '027A0001', '027A1001', '027A1002', '027B0001',
       '027B0002', '027B0003', '027B0004', '027B0005', '027B1001',
       '027B1002', '027B1003', '027B1004', '027B1005', '027B1006',
       '027X0001', '027X1001', '029A0001', '029A1001', '031B0001',
       '031B0002', '031B0003', '031B1001', '031B1002', '031B1003',
       '032A0001', '032A1001', '032B0001', '032B0002', '032B1001',
       '032B1002', '032X0001', '032X1001', '032X1002', '033A0001',
       '033A0002', '033A1001', '033A1002', '033A1003', '033B0001',
       '033B0002', '033B1001', '033B1002', '033B1003', '033X1001',
       '038A0001', '038A1001', '038A1002', '038A1003', '038B0001',
       '038B1001', '039A0001', '039A0002', '039A1001', '039A1002',
       '040B0001', '040B0002', '040B1001', '040D0001', '040D0002',
       '040D1001', '040D1002', '041A1001', '041B0001', '041B0002',
       '041B1002', '041C0001', '041C1001', '041C1002', '041X0001',
       '041X0002', '041X1001', '041X1002', '041X1003', '044B0001',
       '044B1001', '045A0001', '045A0003', '045A0004', '045A1001',
       '045A1002', '045A1003', '045A1004', '045A1005', '046A0001',
       '046A0002', '046A0003', '046A0004', '046A0005', '046A0007',
       '046A0008', '046A1001', '046A1002', '046A1003', '046A1004',
       '046A1005', '046A1006', '046E1001', '051D0001', '051D1001',
       '051X1001', '053B0001', '053B1001', '054A0001', '054A1001',
       '056A0001', '056A1001', '065B0001', '065B1001', '066A0001',
       '066A1001', '066B0001', '066B1001', '066X0001', '066X0002',
       '066X0003', '066X0004', '066X1001', '066X1002', '066X1003',
       '066X1004', '066X1005', '067X0001', '067X0002', '067X0003',
       '067X1001', '067X1002', '068A0001', '068A1001', '069X0001',
       '069X1001', '07470001', '07471001', '076A0001', '076A1001',
       '077A0001', '077A1001', '079A0001', '079A1001', '083A0001',
       '083A0002', '083A1001', '083A1002', '084A0001', '084A0002',
       '084A1001', '084A1002', 'OL77X101', 'PP071001'], dtype=object)

In [38]:
df_stops.sort(['Journey_Pattern_ID','Distance'])

/Users/April/anaconda/envs/comp47350/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  """Entry point for launching an IPython kernel.

        Journey_Pattern_ID  Stop_ID      Distance Line_ID
0                 00010001      226      0.000000     001
2                 00010001      228    232.285714     001
4                 00010001      229    469.898305     001
66                00010001      227    862.014925     001
896               00010001      230   1073.111111     001
69                00010001      231   1330.617978     001
71                00010001     1641   1807.100000     001
612               00010001     1642   2121.025000     001
11                00010001      213   2352.663265     001
668               00010001      214   2657.450000     001
290               00010001     4432   2950.704545     001
242               00010001      119   3170.348837     001
732               00010001       44   3421.977778     001
17                00010001       45   3823.538462     001
19                00010001       46   4072.135593     001
21                00010001       47   4454.492754     001
84                00010001       48   4678.266667     001
24                00010001       49   4980.031250     001
919               00010001       50   5196.666667     001
27                00010001       51   5240.177419     001
29                00010001       52   5418.525424     001
31                00010001      265   6306.583333     001
33                00010001      271   6873.462963     001
35                00010001      340   7288.761006     001
97                00010001      350   7759.078947     001
38                00010001      351   8095.847059     001
40                00010001      352   8316.946237     001
103               00010001      353   8504.924731     001
105               00010001      354   8700.347826     001
107               00010001      355   8980.616667     001
...                    ...      ...           ...     ...
2209023           084A1002     4201   1694.000000     84A
2209025           084A1002     4202   2557.000000     84A
2209180           084A1002     4204   3049.000000     84A
2209030           084A1002     3140   4185.500000     84A
2209032           084A1002     3141   4770.750000     84A
2209242           084A1002     3143   6018.000000     84A
2209192           084A1002     3149   8832.000000     84A
2209196           084A1002     3153   9894.000000     84A
2209198           084A1002     3152   9899.000000     84A
2209202           084A1002     3156  10959.000000     84A
2209094           084A1002     3158  11426.000000     84A
2209098           084A1002     3161  12298.333333     84A
2209053           084A1002     3164  13240.500000     84A
2209157           084A1002     3084  14351.333333     84A
2209165           084A1002      475  15711.000000     84A
2209059           084A1002      473  15859.000000     84A
2209112           084A1002     4705  17054.000000     84A
2209065           084A1002      478  17522.600000     84A
2209308           OL77X101     4714      0.000000     L77
2209311           OL77X101     2427  12551.000000     L77
2209313           OL77X101     2430  13651.000000     L77
2209315           OL77X101     2371  13669.250000     L77
2209318           OL77X101     2373  14712.000000     L77
2209338           OL77X101     1424  18099.000000     L77
2209357           OL77X101     2190  18811.000000     L77
2209375           PP071001     3224    640.000000     P07
2209390           PP071001      476  13714.000000     P07
2209394           PP071001      487  16297.000000     P07
2209399           PP071001      279  19432.000000     P07
2209401           PP071001     4962  20405.000000     P07

[17259 rows x 4 columns]

In [17]:
df_stops.to_csv('journey_stops.csv',index=False)

# Get the timetable for all the Line

In [5]:
df_groupby=df.groupby(['Journey_Pattern_ID','Vehicle_Journey_ID','Date'])
df_first_stop=df_groupby.first()

In [6]:
df_first_stop

                                                   Timestamp  Lon_WGS84  \
Journey_Pattern_ID Vehicle_Journey_ID Date
00010001           4748               2012-11-19  1353320104  -6.261983
                                      2012-11-21  1353492899  -6.261950
                   4750               2012-11-22  1353586477  -6.261950
                   4752               2012-11-19  1353334502  -6.261967
                                      2012-11-20  1353420906  -6.261983
                                      2012-11-21  1353507306  -6.261983
                                      2012-11-22  1353593776  -6.261967
                                      2012-11-23  1353680453  -6.261967
                   4754               2012-11-19  1353341826  -6.262017
                                      2012-11-20  1353428114  -6.261867
                   4756               2012-11-19  1353349024  -6.262017
                                      2012-11-20  1353435645  -6.261933
                                      2012-11-21  1353522469  -6.262000
                                      2012-11-23  1353695003  -6.262289
                   4758               2012-11-19  1353357184  -6.262341
                                      2012-11-20  1353443566  -6.247033
                                      2012-11-21  1353529542  -6.262000
                                      2012-11-22  1353615908  -6.261983
                                      2012-11-23  1353702302  -6.262000
                   4760               2012-11-19  1353363908  -6.262000
                                      2012-11-20  1353450302  -6.262033
                                      2012-11-23  1353709507  -6.262033
                   4767               2012-11-20  1353405678  -6.262341
                                      2012-11-21  1353491727  -6.261833
                                      2012-11-23  1353664506  -6.261850
                   4769               2012-11-19  1353326108  -6.261867
                                      2012-11-20  1353412501  -6.261867
                                      2012-11-23  1353671705  -6.261967
                   4771               2012-11-20  1353419804  -6.261783
                                      2012-11-21  1353506103  -6.261800
...                                                      ...        ...
084X0001           5385               2012-11-22  1353585733  -6.255485
                   5421               2012-11-30  1354295043  -6.251933
                   5424               2012-11-29  1354190424  -6.259240
                   6579               2012-11-30  1354290526  -6.259217
                   7465               2012-11-06  1352217033  -6.259267
                                      2012-11-12  1352735442  -6.259240
084X0002           5381               2012-11-21  1353516220  -6.258200
                   5420               2012-11-30  1354293851  -6.259316
                   5422               2012-11-30  1354300251  -6.259240
                   6164               2012-11-26  1353951872  -6.259240
                   6802               2012-11-14  1352915083  -6.259240
084X1001           5425               2012-11-30  1354281905  -6.063033
084X1002           3418               2012-11-08  1352361086  -6.063617
                   6060               2012-11-23  1353654664  -6.054683
OL77X101           1875               2012-11-20  1353394563  -6.427067
                                      2012-11-22  1353567461  -6.427117
                                      2012-11-23  1353654736  -6.427200
                   1913               2012-11-26  1353913441  -6.422417
                                      2012-11-27  1353999567  -6.427233
                                      2012-11-28  1354086014  -6.427150
                                      2012-11-29  1354172104  -6.427067
                   2079               2012-11-06  1352184905  -6.427134
                                      2012-11-07  1352271489  -6.422100
                                      2012-11-13  1352790866  -6.427217
                                      2012-11-14  1352877668  -6.427383
                                      2012-11-15  1352962754  -6.421633
OL840013           3026               2012-11-19  1353341752  -6.232316
                                      2012-11-21  1353514414  -6.231133
PP071001           12869              2012-11-10  1352534347  -6.128440
                                      2012-11-17  1353138843  -6.129034

                                                  Lat_WGS84 Stop_ID  At_Stop  \
Journey_Pattern_ID Vehicle_Journey_ID Date
00010001           4748               2012-11-19  53.391132     226        1
                                      2012-11-21  53.391167     226        1
                   4750               2012-11-22  53.391182     226        1
                   4752               2012-11-19  53.391167     226        1
                                      2012-11-20  53.391132     226        1
                                      2012-11-21  53.391132     226        1
                                      2012-11-22  53.391182     226        1
                                      2012-11-23  53.391151     226        1
                   4754               2012-11-19  53.391167     226        1
                                      2012-11-20  53.391132     226        1
                   4756               2012-11-19  53.391182     226        1
                                      2012-11-20  53.391182     226        1
                                      2012-11-21  53.391167     226        1
                                      2012-11-23  53.391869     226        0
                   4758               2012-11-19  53.391186     226        0
                                      2012-11-20  53.389782     226        1
                                      2012-11-21  53.391182     226        1
                                      2012-11-22  53.391167     226        1
                                      2012-11-23  53.391201     226        1
                   4760               2012-11-19  53.391151     226        1
                                      2012-11-20  53.391151     226        1
                                      2012-11-23  53.391167     226        1
                   4767               2012-11-20  53.391186     226        0
                                      2012-11-21  53.391182     226        1
                                      2012-11-23  53.391167     226        1
                   4769               2012-11-19  53.391201     226        1
                                      2012-11-20  53.391201     226        1
                                      2012-11-23  53.391201     226        1
                   4771               2012-11-20  53.391132     226        1
                                      2012-11-21  53.391132     226        1
...                                                     ...     ...      ...
084X0001           5385               2012-11-22  53.340488     401        0
                   5421               2012-11-30  53.344734     401        1
                   5424               2012-11-29  53.343990     401        0
                   6579               2012-11-30  53.344166     401        1
                   7465               2012-11-06  53.344166     401        0
                                      2012-11-12  53.343594     401        0
084X0002           5381               2012-11-21  53.346550     401        1
                   5420               2012-11-30  53.344051     401        1
                   5422               2012-11-30  53.343990     401        0
                   6164               2012-11-26  53.344082     401        1
                   6802               2012-11-14  53.344082     401        1
084X1001           5425               2012-11-30  53.070534    4260        1
084X1002           3418               2012-11-08  53.106201    4307        0
                   6060               2012-11-23  53.106266    4307        0
OL77X101           1875               2012-11-20  53.290516    4714        1
                                      2012-11-22  53.290615    4714        1
                                      2012-11-23  53.290718    4714        1
                   1913               2012-11-26  53.287518    4714        1
                                      2012-11-27  53.290817    4714        1
                                      2012-11-28  53.291515    4714        1
                                      2012-11-29  53.290501    4714        1
                   2079               2012-11-06  53.290585    4714        1
                                      2012-11-07  53.287033    4714        1
                                      2012-11-13  53.290783    4714        1
                                      2012-11-14  53.292515    4714        1
                                      2012-11-15  53.283932    4714        1
OL840013           3026               2012-11-19  53.318985    4230        0
                                      2012-11-21  53.318684    4230        0
PP071001           12869              2012-11-10  53.246613    3222        0
                                      2012-11-17  53.246349    3222        1

                                                  First_Stop  Last_Stop  \
Journey_Pattern_ID Vehicle_Journey_ID Date
00010001           4748               2012-11-19         226        380
                                      2012-11-21         226        380
                   4750               2012-11-22         226        380
                   4752               2012-11-19         226        380
                                      2012-11-20         226        380
                                      2012-11-21         226        380
                                      2012-11-22         226        380
                                      2012-11-23         226        380
                   4754               2012-11-19         226        380
                                      2012-11-20         226        380
                   4756               2012-11-19         226        380
                                      2012-11-20         226        380
                                      2012-11-21         226        380
                                      2012-11-23         226        380
                   4758               2012-11-19         226        380
                                      2012-11-20         226        380
                                      2012-11-21         226        380
                                      2012-11-22         226        380
                                      2012-11-23         226        380
                   4760               2012-11-19         226        380
                                      2012-11-20         226        380
                                      2012-11-23         226        380
                   4767               2012-11-20         226        380
                                      2012-11-21         226        380
                                      2012-11-23         226        380
                   4769               2012-11-19         226        380
                                      2012-11-20         226        380
                                      2012-11-23         226        380
                   4771               2012-11-20         226        380
                                      2012-11-21         226        380
...                                                      ...        ...
084X0001           5385               2012-11-22         401       6137
                   5421               2012-11-30         401       6137
                   5424               2012-11-29         401       6137
                   6579               2012-11-30         401       6137
                   7465               2012-11-06         401       6137
                                      2012-11-12         401       6137
084X0002           5381               2012-11-21         401       4306
                   5420               2012-11-30         401       4306
                   5422               2012-11-30         401       4306
                   6164               2012-11-26         401       4306
                   6802               2012-11-14         401       4306
084X1001           5425               2012-11-30        4260        317
084X1002           3418               2012-11-08        4307       4842
                   6060               2012-11-23        4307       4842
OL77X101           1875               2012-11-20        4714        493
                                      2012-11-22        4714        493
                                      2012-11-23        4714        493
                   1913               2012-11-26        4714        493
                                      2012-11-27        4714        493
                                      2012-11-28        4714        493
                                      2012-11-29        4714        493
                   2079               2012-11-06        4714        493
                                      2012-11-07        4714        493
                                      2012-11-13        4714        493
                                      2012-11-14        4714        493
                                      2012-11-15        4714        493
OL840013           3026               2012-11-19        4230       4652
                                      2012-11-21        4230       4652
PP071001           12869              2012-11-10        3222       4962
                                      2012-11-17        3222       4962

                                                  Distance  Trip_Time  \
Journey_Pattern_ID Vehicle_Journey_ID Date
00010001           4748               2012-11-19         0          0
                                      2012-11-21         0          0
                   4750               2012-11-22         0          0
                   4752               2012-11-19         0          0
                                      2012-11-20         0          0
                                      2012-11-21         0          0
                                      2012-11-22         0          0
                                      2012-11-23         0          0
                   4754               2012-11-19         0          0
                                      2012-11-20         0          0
                   4756               2012-11-19         0          0
                                      2012-11-20         0          0
                                      2012-11-21         0          0
                                      2012-11-23         0          0
                   4758               2012-11-19         0          0
                                      2012-11-20         0          0
                                      2012-11-21         0          0
                                      2012-11-22         0          0
                                      2012-11-23         0          0
                   4760               2012-11-19         0          0
                                      2012-11-20         0          0
                                      2012-11-23         0          0
                   4767               2012-11-20         0          0
                                      2012-11-21         0          0
                                      2012-11-23         0          0
                   4769               2012-11-19         0          0
                                      2012-11-20         0          0
                                      2012-11-23         0          0
                   4771               2012-11-20         0          0
                                      2012-11-21         0          0
...                                                    ...        ...
084X0001           5385               2012-11-22         0          0
                   5421               2012-11-30         0          0
                   5424               2012-11-29         0          0
                   6579               2012-11-30         0          0
                   7465               2012-11-06         0          0
                                      2012-11-12         0          0
084X0002           5381               2012-11-21         0          0
                   5420               2012-11-30         0          0
                   5422               2012-11-30         0          0
                   6164               2012-11-26         0          0
                   6802               2012-11-14         0          0
084X1001           5425               2012-11-30         0          0
084X1002           3418               2012-11-08         0          0
                   6060               2012-11-23         0          0
OL77X101           1875               2012-11-20         0          0
                                      2012-11-22         0          0
                                      2012-11-23         0          0
                   1913               2012-11-26         0          0
                                      2012-11-27         0          0
                                      2012-11-28         0          0
                                      2012-11-29         0          0
                   2079               2012-11-06         0          0
                                      2012-11-07         0          0
                                      2012-11-13         0          0
                                      2012-11-14         0          0
                                      2012-11-15         0          0
OL840013           3026               2012-11-19         0          0
                                      2012-11-21         0          0
PP071001           12869              2012-11-10         0          0
                                      2012-11-17         0          0

                                                             datetime  \
Journey_Pattern_ID Vehicle_Journey_ID Date
00010001           4748               2012-11-19  2012-11-19 10:15:04
                                      2012-11-21  2012-11-21 10:14:59
                   4750               2012-11-22  2012-11-22 12:14:37
                   4752               2012-11-19  2012-11-19 14:15:02
                                      2012-11-20  2012-11-20 14:15:06
                                      2012-11-21  2012-11-21 14:15:06
                                      2012-11-22  2012-11-22 14:16:16
                                      2012-11-23  2012-11-23 14:20:53
                   4754               2012-11-19  2012-11-19 16:17:06
                                      2012-11-20  2012-11-20 16:15:14
                   4756               2012-11-19  2012-11-19 18:17:04
                                      2012-11-20  2012-11-20 18:20:45
                                      2012-11-21  2012-11-21 18:27:49
                                      2012-11-23  2012-11-23 18:23:23
                   4758               2012-11-19  2012-11-19 20:33:04
                                      2012-11-20  2012-11-20 20:32:46
                                      2012-11-21  2012-11-21 20:25:42
                                      2012-11-22  2012-11-22 20:25:08
                                      2012-11-23  2012-11-23 20:25:02
                   4760               2012-11-19  2012-11-19 22:25:08
                                      2012-11-20  2012-11-20 22:25:02
                                      2012-11-23  2012-11-23 22:25:07
                   4767               2012-11-20  2012-11-20 10:01:18

In [7]:
df_first_stop.reset_index(inplace=True)

In [8]:
df_first_stop.head()

,Journey_Pattern_ID,Vehicle_Journey_ID,Date,Timestamp,Lon_WGS84,Lat_WGS84,Stop_ID,At_Stop,First_Stop,Last_Stop,...,Trip_Time,datetime,HourOfDay,day_of_week,midweek,time_bin,cloud,rain,temp,wind
0,00010001,4748,2012-11-19,1353320104,-6.261983,53.391132,226,1,226,380,...,0,2012-11-19 10:15:04,10,Monday,0,am,6.88,0.11,12.40,15.75
1,00010001,4748,2012-11-21,1353492899,-6.261950,53.391167,226,1,226,380,...,0,2012-11-21 10:14:59,10,Wednesday,0,am,4.75,0.00,7.12,5.88
2,00010001,4750,2012-11-22,1353586477,-6.261950,53.391182,226,1,226,380,...,0,2012-11-22 12:14:37,12,Thursday,0,am,8.00,0.60,9.15,16.38
3,00010001,4752,2012-11-19,1353334502,-6.261967,53.391167,226,1,226,380,...,0,2012-11-19 14:15:02,14,Monday,0,pm,6.62,0.00,11.94,14.25
4,00010001,4752,2012-11-20,1353420906,-6.261983,53.391132,226,1,226,380,...,0,2012-11-20 14:15:06,14,Tuesday,0,pm,3.12,0.00,10.07,17.00

In [9]:
df_first_stop.sort('Journey_Pattern_ID')

/Users/April/anaconda/envs/comp47350/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  """Entry point for launching an IPython kernel.

,Journey_Pattern_ID,Vehicle_Journey_ID,Date,Timestamp,Lon_WGS84,Lat_WGS84,Stop_ID,At_Stop,First_Stop,Last_Stop,...,Trip_Time,datetime,HourOfDay,day_of_week,midweek,time_bin,cloud,rain,temp,wind
0,00010001,4748,2012-11-19,1353320104,-6.261983,53.391132,226,1,226,380,...,0,2012-11-19 10:15:04,10,Monday,0,am,6.88,0.11,12.40,15.75
385,00010001,5494,2012-11-12,1352711730,-6.261900,53.391151,226,1,226,380,...,0,2012-11-12 09:15:30,9,Monday,0,am,7.50,0.36,10.62,9.88
384,00010001,5494,2012-11-08,1352366100,-6.262033,53.391167,226,1,226,380,...,0,2012-11-08 09:15:00,9,Thursday,0,am,3.62,0.00,7.81,13.12
383,00010001,5494,2012-11-07,1352279711,-6.261983,53.391167,226,1,226,380,...,0,2012-11-07 09:15:11,9,Wednesday,0,am,6.75,0.00,9.22,15.75
382,00010001,5494,2012-11-06,1352193606,-6.261933,53.391167,226,1,226,380,...,0,2012-11-06 09:20:06,9,Tuesday,0,am,6.88,0.00,7.55,16.25
381,00010001,5490,2012-11-08,1352401065,-6.261867,53.391151,226,1,226,380,...,0,2012-11-08 18:57:45,18,Thursday,0,pm,6.12,0.00,9.36,10.50
380,00010001,5490,2012-11-07,1352313486,-6.262000,53.391182,226,1,226,380,...,0,2012-11-07 18:38:06,18,Wednesday,0,pm,7.00,0.00,10.19,17.12
379,00010001,5490,2012-11-06,1352226995,-6.262000,53.391182,226,1,226,380,...,0,2012-11-06 18:36:35,18,Tuesday,0,pm,6.38,0.00,9.19,17.62
378,00010001,5488,2012-11-12,1352738105,-6.261983,53.391182,226,1,226,380,...,0,2012-11-12 16:35:05,16,Monday,0,pm,6.50,0.00,13.06,13.88
377,00010001,5488,2012-11-07,1352306100,-6.262190,53.391178,226,1,226,380,...,0,2012-11-07 16:35:00,16,Wednesday,0,pm,7.00,0.00,10.19,17.12
376,00010001,5486,2012-11-16,1353076677,-6.261950,53.391167,226,1,226,380,...,0,2012-11-16 14:37:57,14,Friday,0,pm,7.62,0.00,7.55,4.75
375,00010001,5486,2012-11-15,1352990109,-6.262084,53.391151,226,1,226,380,...,0,2012-11-15 14:35:09,14,Thursday,0,pm,5.12,0.00,10.36,6.75
374,00010001,5486,2012-11-13,1352817506,-6.262050,53.391132,226,1,226,380,...,0,2012-11-13 14:38:26,14,Tuesday,0,pm,7.50,0.01,12.95,18.25
373,00010001,5486,2012-11-12,1352730902,-6.262084,53.391167,226,1,226,380,...,0,2012-11-12 14:35:02,14,Monday,0,pm,6.50,0.00,13.06,13.88
372,00010001,5486,2012-11-09,1352471789,-6.261950,53.391151,226,1,226,380,...,0,2012-11-09 14:36:29,14,Friday,0,pm,6.75,0.00,7.88,11.12
371,00010001,5486,2012-11-08,1352385304,-6.261917,53.391182,226,1,226,380,...,0,2012-11-08 14:35:04,14,Thursday,0,pm,6.12,0.00,9.36,10.50
370,00010001,5486,2012-11-07,1352298910,-6.261950,53.391167,226,1,226,380,...,0,2012-11-07 14:35:10,14,Wednesday,0,pm,7.00,0.00,10.19,17.12
369,00010001,5486,2012-11-06,1352212509,-6.261983,53.391167,226,1,226,380,...,0,2012-11-06 14:35:09,14,Tuesday,0,pm,6.38,0.00,9.19,17.62
355,00010001,5475,2012-11-15,1353020104,-6.262017,53.391167,226,1,226,380,...,0,2012-11-15 22:55:04,22,Thursday,0,late_pm,5.67,0.00,7.83,5.67
356,00010001,5482,2012-11-06,1352198107,-6.262000,53.391167,226,1,226,380,...,0,2012-11-06 10:35:07,10,Tuesday,0,am,6.88,0.00,7.55,16.25
357,00010001,5482,2012-11-07,1352284501,-6.262017,53.391167,226,1,226,380,...,0,2012-11-07 10:35:01,10,Wednesday,0,am,6.75,0.00,9.22,15.75
358,00010001,5482,2012-11-08,1352371125,-6.261817,53.391151,226,1,226,380,...,0,2012-11-08 10:38:45,10,Thursday,0,am,3.62,0.00,7.81,13.12
359,00010001,5482,2012-11-09,1352457307,-6.262067,53.391132,226,1,226,380,...,0,2012-11-09 10:35:07,10,Friday,0,am,7.50,0.68,8.57,14.25
360,00010001,5482,2012-11-12,1352716509,-6.262000,53.391167,226,1,226,380,...,0,2012-11-12 10:35:09,10,Monday,0,am,7.50,0.36,10.62,9.88
386,00010001,5494,2012-11-13,1352798227,-6.261933,53.391167,226,1,226,380,...,0,2012-11-13 09:17:07,9,Tuesday,0,am,7.38,0.00,12.70,18.50
361,00010001,5482,2012-11-16,1353062104,-6.262017,53.391167,226,1,226,380,...,0,2012-11-16 10:35:04,10,Friday,0,am,6.12,0.00,5.78,2.62
363,00010001,5484,2012-11-07,1352291709,-6.261983,53.391167,226,1,226,380,...,0,2012-11-07 12:35:09,12,Wednesday,0,am,6.75,0.00,9.22,15.75
364,00010001,5484,2012-11-08,1352378104,-6.261950,53.391167,226,1,226,380,...,0,2012-11-08 12:35:04,12,Thursday,0,am,3.62,0.00,7.81,13.12
365,00010001,5484,2012-11-12,1352723710,-6.262067,53.391182,226,1,226,380,...,0,2012-11-12 12:35:10,12,Monday,0,am,7.50,0.36,10.62,9.88
366,00010001,5484,2012-11-13,1352810105,-6.262100,53.391201,226,1,226,380,...,0,2012-11-13 12:35:05,12,Tuesday,0,am,7.38,0.00,12.70,18.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115156,084X0001,7465,2012-11-06,1352217033,-6.259267,53.344166,401,0,401,6137,...,0,2012-11-06 15:50:33,15,Tuesday,0,pm,6.38,0.00,9.19,17.62
115155,084X0001,6579,2012-11-30,1354290526,-6.259217,53.344166,401,1,401,6137,...,0,2012-11-30 15:48:46,15,Friday,0,pm,4.12,0.00,4.17,5.00
115151,084X0001,5385,2012-11-21,1353499322,-6.255117,53.342312,401,0,401,6137,...,0,2012-11-21 12:02:02,12,Wednesday,0,am,4.75,0.00,7.12,5.88
115153,084X0001,5421,2012-11-30,1354295043,-6.251933,53.344734,401,1,401,6137,...,0,2012-11-30 17:04:03,17,Friday,0,pm,4.12,0.00,4.17,5.00
115152,084X0001,5385,2012-11-22,1353585733,-6.255485,53.340488,401,0,401,6137,...,0,2012-11-22 12:02:13,12,Thursday,0,am,8.00,0.60,9.15,16.38
115154,084X0001,5424,2012-11-29,1354190424,-6.259240,53.343990,401,0,401,6137,...,0,2012-11-29 12:00:24,12,Thursday,0,am,5.50,0.00,0.66,7.50
115161,084X0002,6164,2012-11-26,1353951872,-6.259240,53.344082,401,1,401,4306,...,0,2012-11-26 17:44:32,17,Monday,0,pm,4.00,0.00,6.14,16.75
115160,084X0002,5422,2012-11-30,1354300251,-6.259240,53.343990,401,0,401,4306,...,0,2012-11-30 18:30:51,18,Friday,0,pm,4.12,0.00,4.17,5.00
115162,084X0002,6802,2012-11-14,1352915083,-6.259240,53.344082,401,1,401,4306,...,0,2012-11-14 17:44:43,17,Wednesday,0,pm,5.75,0.00,11.15,8.38
115158,084X0002,5381,2012-11-21,1353516220,-6.258200,53.346550,401,1,401,4306,...,0,2012-11-21 16:43:40,16,Wednesday,0,pm,2.62,0.01,9.25,10.75
115159,084X0002,5420,2012-11-30,1354293851,-6.259316,53.344051,401,1,401,4306,...,0,2012-11-30 16:44:11,16,Friday,0,pm,4.12,0.00,4.17,5.00
115163,084X1001,5425,2012-11-30,1354281905,-6.063033,53.070534,4260,1,4260,317,...,0,2012-11-30 13:25:05,13,Friday,0,pm,4.12,0.00,4.17,5.00
115164,084X1002,3418,2012-11-08,1352361086,-6.063617,53.106201,4307,0,4307,4842,...,0,2012-11-08 07:51:26,7,Thursday,0,am,3.62,0.00,7.81,13.12
115165,084X1002,6060,2012-11-23,1353654664,-6.054683,53.106266,4307,0,4307,4842,...,0,2012-11-23 07:11:04,7,Friday,0,am,3.50,0.00,5.61,11.88
115177,OL77X101,2079,2012-11-15,1352962754,-6.421633,53.283932,4714,1,4714,493,...,0,2012-11-15 06:59:14,6,Thursday,0,am,6.38,0.00,9.71,3.75
115176,OL77X101,2079,2012-11-14,1352877668,-6.427383,53.292515,4714,1,4714,493,...,0,2012-11-14 07:21:08,7,Wednesday,0,am,6.62,0.00,11.65,10.25
115175,OL77X101,2079,2012-11-13,1352790866,-6.427217,53.290783,4714,1,4714,493,...,0,2012-11-13 07:14:26,7,Tuesday,0,am,7.38,0.00,12.70,18.50
115174,OL77X101,2079,2012-11-07,1352271489,-6.422100,53.287033,4714,1,4714,493,...,0,2012-11-07 06:58:09,6,Wednesday,0,am,6.75,0.00,9.22,15.75
115173,OL77X101,2079,2012-11-06,1352184905,-6.427134,53.290585,4714,1,4714,493,...,0,2012-11-06 06:55:05,6,Tuesday,0,am,6.88,0.00,7.55,16.25
115172,OL77X101,1913,2012-11-29,1354172104,-6.427067,53.290501,4714,1,4714,493,...,0,2012-11-29 06:55:04,6,Thursday,0,am,5.50,0.00,0.66,7.50
115171,OL77X101,1913,2012-11-28,1354086014,-6.427150,53.291515,4714,1,4714,493,...,0,2012-11-28 07:00:14,7,Wednesday,0,am,1.00,0.00,1.42,8.00
115169,OL77X101,1913,2012-11-26,1353913441,-6.422417,53.287518,4714,1,4714,493,...,0,2012-11-26 07:04:01,7,Monday,0,am,6.62,0.05,5.20,17.50
115168,OL77X101,1875,2012-11-23,1353654736,-6.427200,53.290718,4714,1,4714,493,...,0,2012-11-23 07:12:16,7,Friday,0,am,3.50,0.00,5.61,11.88
115167,OL77X101,1875,2012-11-22,1353567461,-6.427117,53.290615,4714,1,4714,493,...,0,2012-11-22 06:57:41,6,Thursday,0,am,8.00,0.60,9.15,16.38
115166,OL77X101,1875,2012-11-20,1353394563,-6.427067,53.290516,4714,1,4714,493,...,0,2012-11-20 06:56:03,6,Tuesday,0,am,6.12,0.00,12.03,10.38
115170,OL77X101,1913,2012-11-27,1353999567,-6.427233,53.290817,4714,1,4714,493,...,0,2012-11-27 06:59:27,6,Tuesday,0,am,4.88,0.00,4.17,14.25
115178,OL840013,3026,2012-11-19,1353341752,-6.232316,53.318985,4230,0,4230,4652,...,0,2012-11-19 16:15:52,16,Monday,0,pm,6.62,0.00,11.94,14.25
115179,OL840013,3026,2012-11-21,1353514414,-6.231133,53.318684,4230,0,4230,4652,...,0,2012-11-21 16:13:34,16,Wednesday,0,pm,2.62,0.01,9.25,10.75
115180,PP071001,12869,2012-11-10,1352534347,-6.128440,53.246613,3222,0,3222,4962,...,0,2012-11-10 07:59:07,7,Saturday,1,am,3.75,0.00,4.96,10.25
115181,PP071001,12869,2012-11-17,1353138843,-6.129034,53.246349,3222,1,3222,4962,...,0,2012-11-17 07:54:03,7,Saturday,1,am,3.00,0.00,4.85,10.38

In [46]:
df_timetable=df_first_stop[['Journey_Pattern_ID','Timestamp','day_of_week','datetime','First_Stop','Last_Stop']]

In [47]:
# Add midweek feature 
df_timetable['week_cate'] = df_timetable['day_of_week'].map({'Monday': 'Workday', 'Tuesday': 'Workday','Wednesday':'Workday','Thursday':'Workday','Friday': 'Workday','Saturday':'Saturday','Sunday':'Sunday'})

/Users/April/anaconda/envs/comp47350/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [48]:
df_timetable.sort('Journey_Pattern_ID')

/Users/April/anaconda/envs/comp47350/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  """Entry point for launching an IPython kernel.

,Journey_Pattern_ID,Timestamp,day_of_week,datetime,First_Stop,Last_Stop,week_cate
0,00010001,1353320104,Monday,2012-11-19 10:15:04,226,380,Workday
385,00010001,1352711730,Monday,2012-11-12 09:15:30,226,380,Workday
384,00010001,1352366100,Thursday,2012-11-08 09:15:00,226,380,Workday
383,00010001,1352279711,Wednesday,2012-11-07 09:15:11,226,380,Workday
382,00010001,1352193606,Tuesday,2012-11-06 09:20:06,226,380,Workday
381,00010001,1352401065,Thursday,2012-11-08 18:57:45,226,380,Workday
380,00010001,1352313486,Wednesday,2012-11-07 18:38:06,226,380,Workday
379,00010001,1352226995,Tuesday,2012-11-06 18:36:35,226,380,Workday
378,00010001,1352738105,Monday,2012-11-12 16:35:05,226,380,Workday
377,00010001,1352306100,Wednesday,2012-11-07 16:35:00,226,380,Workday
376,00010001,1353076677,Friday,2012-11-16 14:37:57,226,380,Workday
375,00010001,1352990109,Thursday,2012-11-15 14:35:09,226,380,Workday
374,00010001,1352817506,Tuesday,2012-11-13 14:38:26,226,380,Workday
373,00010001,1352730902,Monday,2012-11-12 14:35:02,226,380,Workday
372,00010001,1352471789,Friday,2012-11-09 14:36:29,226,380,Workday
371,00010001,1352385304,Thursday,2012-11-08 14:35:04,226,380,Workday
370,00010001,1352298910,Wednesday,2012-11-07 14:35:10,226,380,Workday
369,00010001,1352212509,Tuesday,2012-11-06 14:35:09,226,380,Workday
355,00010001,1353020104,Thursday,2012-11-15 22:55:04,226,380,Workday
356,00010001,1352198107,Tuesday,2012-11-06 10:35:07,226,380,Workday
357,00010001,1352284501,Wednesday,2012-11-07 10:35:01,226,380,Workday
358,00010001,1352371125,Thursday,2012-11-08 10:38:45,226,380,Workday
359,00010001,1352457307,Friday,2012-11-09 10:35:07,226,380,Workday
360,00010001,1352716509,Monday,2012-11-12 10:35:09,226,380,Workday
386,00010001,1352798227,Tuesday,2012-11-13 09:17:07,226,380,Workday
361,00010001,1353062104,Friday,2012-11-16 10:35:04,226,380,Workday
363,00010001,1352291709,Wednesday,2012-11-07 12:35:09,226,380,Workday
364,00010001,1352378104,Thursday,2012-11-08 12:35:04,226,380,Workday
365,00010001,1352723710,Monday,2012-11-12 12:35:10,226,380,Workday
366,00010001,1352810105,Tuesday,2012-11-13 12:35:05,226,380,Workday
...,...,...,...,...,...,...,...
115156,084X0001,1352217033,Tuesday,2012-11-06 15:50:33,401,6137,Workday
115155,084X0001,1354290526,Friday,2012-11-30 15:48:46,401,6137,Workday
115151,084X0001,1353499322,Wednesday,2012-11-21 12:02:02,401,6137,Workday
115153,084X0001,1354295043,Friday,2012-11-30 17:04:03,401,6137,Workday
115152,084X0001,1353585733,Thursday,2012-11-22 12:02:13,401,6137,Workday
115154,084X0001,1354190424,Thursday,2012-11-29 12:00:24,401,6137,Workday
115161,084X0002,1353951872,Monday,2012-11-26 17:44:32,401,4306,Workday
115160,084X0002,1354300251,Friday,2012-11-30 18:30:51,401,4306,Workday
115162,084X0002,1352915083,Wednesday,2012-11-14 17:44:43,401,4306,Workday
115158,084X0002,1353516220,Wednesday,2012-11-21 16:43:40,401,4306,Workday
115159,084X0002,1354293851,Friday,2012-11-30 16:44:11,401,4306,Workday
115163,084X1001,1354281905,Friday,2012-11-30 13:25:05,4260,317,Workday
115164,084X1002,1352361086,Thursday,2012-11-08 07:51:26,4307,4842,Workday
115165,084X1002,1353654664,Friday,2012-11-23 07:11:04,4307,4842,Workday
115177,OL77X101,1352962754,Thursday,2012-11-15 06:59:14,4714,493,Workday
115176,OL77X101,1352877668,Wednesday,2012-11-14 07:21:08,4714,493,Workday
115175,OL77X101,1352790866,Tuesday,2012-11-13 07:14:26,4714,493,Workday
115174,OL77X101,1352271489,Wednesday,2012-11-07 06:58:09,4714,493,Workday
115173,OL77X101,1352184905,Tuesday,2012-11-06 06:55:05,4714,493,Workday
115172,OL77X101,1354172104,Thursday,2012-11-29 06:55:04,4714,493,Workday
115171,OL77X101,1354086014,Wednesday,2012-11-28 07:00:14,4714,493,Workday
115169,OL77X101,1353913441,Monday,2012-11-26 07:04:01,4714,493,Workday
115168,OL77X101,1353654736,Friday,2012-11-23 07:12:16,4714,493,Workday
115167,OL77X101,1353567461,Thursday,2012-11-22 06:57:41,4714,493,Workday
115166,OL77X101,1353394563,Tuesday,2012-11-20 06:56:03,4714,493,Workday
115170,OL77X101,1353999567,Tuesday,2012-11-27 06:59:27,4714,493,Workday
115178,OL840013,1353341752,Monday,2012-11-19 16:15:52,4230,4652,Workday
115179,OL840013,1353514414,Wednesday,2012-11-21 16:13:34,4230,4652,Workday
115180,PP071001,1352534347,Saturday,2012-11-10 07:59:07,3222,4962,Saturday
115181,PP071001,1353138843,Saturday,2012-11-17 07:54:03,3222,4962,Saturday

In [49]:
#df_timetable['datetime']=pd.to_datetime(df_timetable['datetime'])

#df_timetable['Time']=df_timetable['datetime'].dt.time

In [50]:
ns_five=5*60
df_timetable['Time']=pd.to_datetime(((df_timetable['Timestamp'] // ns_five + 1 ) * ns_five),unit='s')

/Users/April/anaconda/envs/comp47350/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [51]:
df_timetable['Time']=df_timetable['Time'].dt.time

/Users/April/anaconda/envs/comp47350/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [52]:
df_timetable.sort('Journey_Pattern_ID')

/Users/April/anaconda/envs/comp47350/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  """Entry point for launching an IPython kernel.

,Journey_Pattern_ID,Timestamp,day_of_week,datetime,First_Stop,Last_Stop,week_cate,Time
0,00010001,1353320104,Monday,2012-11-19 10:15:04,226,380,Workday,10:20:00
385,00010001,1352711730,Monday,2012-11-12 09:15:30,226,380,Workday,09:20:00
384,00010001,1352366100,Thursday,2012-11-08 09:15:00,226,380,Workday,09:20:00
383,00010001,1352279711,Wednesday,2012-11-07 09:15:11,226,380,Workday,09:20:00
382,00010001,1352193606,Tuesday,2012-11-06 09:20:06,226,380,Workday,09:25:00
381,00010001,1352401065,Thursday,2012-11-08 18:57:45,226,380,Workday,19:00:00
380,00010001,1352313486,Wednesday,2012-11-07 18:38:06,226,380,Workday,18:40:00
379,00010001,1352226995,Tuesday,2012-11-06 18:36:35,226,380,Workday,18:40:00
378,00010001,1352738105,Monday,2012-11-12 16:35:05,226,380,Workday,16:40:00
377,00010001,1352306100,Wednesday,2012-11-07 16:35:00,226,380,Workday,16:40:00
376,00010001,1353076677,Friday,2012-11-16 14:37:57,226,380,Workday,14:40:00
375,00010001,1352990109,Thursday,2012-11-15 14:35:09,226,380,Workday,14:40:00
374,00010001,1352817506,Tuesday,2012-11-13 14:38:26,226,380,Workday,14:40:00
373,00010001,1352730902,Monday,2012-11-12 14:35:02,226,380,Workday,14:40:00
372,00010001,1352471789,Friday,2012-11-09 14:36:29,226,380,Workday,14:40:00
371,00010001,1352385304,Thursday,2012-11-08 14:35:04,226,380,Workday,14:40:00
370,00010001,1352298910,Wednesday,2012-11-07 14:35:10,226,380,Workday,14:40:00
369,00010001,1352212509,Tuesday,2012-11-06 14:35:09,226,380,Workday,14:40:00
355,00010001,1353020104,Thursday,2012-11-15 22:55:04,226,380,Workday,23:00:00
356,00010001,1352198107,Tuesday,2012-11-06 10:35:07,226,380,Workday,10:40:00
357,00010001,1352284501,Wednesday,2012-11-07 10:35:01,226,380,Workday,10:40:00
358,00010001,1352371125,Thursday,2012-11-08 10:38:45,226,380,Workday,10:40:00
359,00010001,1352457307,Friday,2012-11-09 10:35:07,226,380,Workday,10:40:00
360,00010001,1352716509,Monday,2012-11-12 10:35:09,226,380,Workday,10:40:00
386,00010001,1352798227,Tuesday,2012-11-13 09:17:07,226,380,Workday,09:20:00
361,00010001,1353062104,Friday,2012-11-16 10:35:04,226,380,Workday,10:40:00
363,00010001,1352291709,Wednesday,2012-11-07 12:35:09,226,380,Workday,12:40:00
364,00010001,1352378104,Thursday,2012-11-08 12:35:04,226,380,Workday,12:40:00
365,00010001,1352723710,Monday,2012-11-12 12:35:10,226,380,Workday,12:40:00
366,00010001,1352810105,Tuesday,2012-11-13 12:35:05,226,380,Workday,12:40:00
...,...,...,...,...,...,...,...,...
115156,084X0001,1352217033,Tuesday,2012-11-06 15:50:33,401,6137,Workday,15:55:00
115155,084X0001,1354290526,Friday,2012-11-30 15:48:46,401,6137,Workday,15:50:00
115151,084X0001,1353499322,Wednesday,2012-11-21 12:02:02,401,6137,Workday,12:05:00
115153,084X0001,1354295043,Friday,2012-11-30 17:04:03,401,6137,Workday,17:05:00
115152,084X0001,1353585733,Thursday,2012-11-22 12:02:13,401,6137,Workday,12:05:00
115154,084X0001,1354190424,Thursday,2012-11-29 12:00:24,401,6137,Workday,12:05:00
115161,084X0002,1353951872,Monday,2012-11-26 17:44:32,401,4306,Workday,17:45:00
115160,084X0002,1354300251,Friday,2012-11-30 18:30:51,401,4306,Workday,18:35:00
115162,084X0002,1352915083,Wednesday,2012-11-14 17:44:43,401,4306,Workday,17:45:00
115158,084X0002,1353516220,Wednesday,2012-11-21 16:43:40,401,4306,Workday,16:45:00
115159,084X0002,1354293851,Friday,2012-11-30 16:44:11,401,4306,Workday,16:45:00
115163,084X1001,1354281905,Friday,2012-11-30 13:25:05,4260,317,Workday,13:30:00
115164,084X1002,1352361086,Thursday,2012-11-08 07:51:26,4307,4842,Workday,07:55:00
115165,084X1002,1353654664,Friday,2012-11-23 07:11:04,4307,4842,Workday,07:15:00
115177,OL77X101,1352962754,Thursday,2012-11-15 06:59:14,4714,493,Workday,07:00:00
115176,OL77X101,1352877668,Wednesday,2012-11-14 07:21:08,4714,493,Workday,07:25:00
115175,OL77X101,1352790866,Tuesday,2012-11-13 07:14:26,4714,493,Workday,07:15:00
115174,OL77X101,1352271489,Wednesday,2012-11-07 06:58:09,4714,493,Workday,07:00:00
115173,OL77X101,1352184905,Tuesday,2012-11-06 06:55:05,4714,493,Workday,07:00:00
115172,OL77X101,1354172104,Thursday,2012-11-29 06:55:04,4714,493,Workday,07:00:00
115171,OL77X101,1354086014,Wednesday,2012-11-28 07:00:14,4714,493,Workday,07:05:00
115169,OL77X101,1353913441,Monday,2012-11-26 07:04:01,4714,493,Workday,07:05:00
115168,OL77X101,1353654736,Friday,2012-11-23 07:12:16,4714,493,Workday,07:15:00
115167,OL77X101,1353567461,Thursday,2012-11-22 06:57:41,4714,493,Workday,07:00:00
115166,OL77X101,1353394563,Tuesday,2012-11-20 06:56:03,4714,493,Workday,07:00:00
115170,OL77X101,1353999567,Tuesday,2012-11-27 06:59:27,4714,493,Workday,07:00:00
115178,OL840013,1353341752,Monday,2012-11-19 16:15:52,4230,4652,Workday,16:20:00
115179,OL840013,1353514414,Wednesday,2012-11-21 16:13:34,4230,4652,Workday,16:15:00
115180,PP071001,1352534347,Saturday,2012-11-10 07:59:07,3222,4962,Saturday,08:00:00
115181,PP071001,1353138843,Saturday,2012-11-17 07:54:03,3222,4962,Saturday,07:55:00

In [53]:
import numba 

@numba.jit
def delete_error(df):
# Write the function to check the first stop and last stop

    df_grouped = df.groupby(['Journey_Pattern_ID','Time'])
    vj_groups = []
    for jer_name, jer_group in df_grouped:
        number=jer_group.shape[0]
        #print(number)
        if number>1:       
            vj_groups.append(jer_group )
    return pd.concat(vj_groups)
df_timetable=delete_error(df_timetable)

In [54]:
df_timetable.shape

(110297, 8)

In [55]:
# Only keep the first one 
df_timetable = df_timetable.drop_duplicates(['Journey_Pattern_ID','week_cate','Time'])
df_timetable.shape

(24244, 8)

In [72]:
df_timetable.sort('Journey_Pattern_ID')

/Users/April/anaconda/envs/comp47350/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  """Entry point for launching an IPython kernel.

       Journey_Pattern_ID  First_Stop  Last_Stop week_cate      Time Line_ID
472              00010001         226        380  Saturday  08:30:00     001
203              00010001         226        380   Workday  19:25:00     001
147              00010001         226        380   Workday  19:05:00     001
518              00010001         226        380    Sunday  19:00:00     001
491              00010001         226        380  Saturday  19:00:00     001
62               00010001         226        380   Workday  19:00:00     001
178              00010001         226        380   Workday  18:45:00     001
108              00010001         226        380   Workday  18:40:00     001
524              00010001         226        380    Sunday  18:30:00     001
505              00010001         226        380  Saturday  18:30:00     001
12               00010001         226        380   Workday  18:30:00     001
11               00010001         226        380   Workday  18:25:00     001
10               00010001         226        380   Workday  18:20:00     001
111              00010001         226        380   Workday  18:05:00     001
165              00010001         226        380   Workday  17:50:00     001
498              00010001         226        380  Saturday  17:45:00     001
167              00010001         226        380   Workday  17:45:00     001
221              00010001         226        380   Workday  17:40:00     001
202              00010001         226        380   Workday  17:25:00     001
198              00010001         226        380   Workday  17:20:00     001
517              00010001         226        380    Sunday  17:00:00     001
490              00010001         226        380  Saturday  17:00:00     001
103              00010001         226        380   Workday  16:45:00     001
102              00010001         226        380   Workday  16:40:00     001
523              00010001         226        380    Sunday  16:30:00     001
8                00010001         226        380   Workday  16:20:00     001
31               00010001         226        380   Workday  16:05:00     001
547              00010001         226        380    Sunday  16:00:00     001
132              00010001         226        380   Workday  19:30:00     001
530              00010001         226        380    Sunday  19:30:00     001
...                   ...         ...        ...       ...       ...     ...
115037           084A0001        7188       4168   Workday  17:15:00     84A
115036           084A0001        7188       4168   Workday  17:10:00     84A
115018           084A0001        7188       4168   Workday  16:15:00     84A
115058           084A0001        7188       4168   Workday  09:00:00     84A
115013           084A0001        7188       4168   Workday  09:10:00     84A
115016           084A0001        7188       4168   Workday  09:05:00     84A
115020           084A0001        7188       4168   Workday  08:15:00     84A
115009           084A0001        7188       4168   Workday  08:10:00     84A
115010           084A0001        7188       4168   Workday  07:00:00     84A
115034           084A0001        7188       4168   Workday  16:10:00     84A
115088           084A0002         422       4168   Workday  09:45:00     84A
115081           084A0002         422       4168   Workday  09:50:00     84A
115085           084A0002         422       4168   Workday  09:55:00     84A
115098           084A1001        4168       7188   Workday  18:30:00     84A
115111           084A1001        4168       7188   Workday  18:25:00     84A
115097           084A1001        4168       7188   Workday  15:30:00     84A
115093           084A1001        4168       7188   Workday  09:25:00     84A
115091           084A1001        4168       7188   Workday  07:00:00     84A
115094           084A1001        4168       7188   Workday  06:20:00     84A
115090           084A1001        4168       7188   Workday  07:05:00     84A
115135           084A1002        4168        478   Workday  10:25:00     84A
115139           084A1002        4168        478   Workday  10:30:00     84A
115141           084A1002        4168        478   Workday  10:35:00     84A
115151           084X0001         401       6137   Workday  12:05:00     84X
115156           084X0001         401       6137   Workday  15:55:00     84X
115158           084X0002         401       4306   Workday  16:45:00     84X
115161           084X0002         401       4306   Workday  17:45:00     84X
115169           OL77X101        4714        493   Workday  07:05:00     L77
115166           OL77X101        4714        493   Workday  07:00:00     L77
115168           OL77X101        4714        493   Workday  07:15:00     L77

[24244 rows x 6 columns]

In [57]:
pd.unique(df_timetable['day_of_week'])

array(['Saturday', 'Monday', 'Tuesday', 'Thursday', 'Wednesday', 'Sunday',
       'Friday'], dtype=object)

In [58]:
df_timetable.dtypes

Journey_Pattern_ID    object
Timestamp              int64
day_of_week           object
datetime              object
First_Stop             int64
Last_Stop              int64
week_cate             object
Time                  object
dtype: object

In [70]:
df_timetable['Journey_Pattern_ID']=df_timetable['Journey_Pattern_ID'].astype(str)
df_timetable.drop(['Timestamp'],axis=1,inplace=True)

In [79]:
df_timetable['Line_ID']= df_timetable['Journey_Pattern_ID'].apply(lambda x:x[1:4:].strip("0"))

In [80]:
df_timetable.head(1)

    Journey_Pattern_ID  First_Stop  Last_Stop week_cate      Time Line_ID
472           00010001         226        380  Saturday  08:30:00       1

In [63]:
df_timetable.drop(['datetime','day_of_week'],axis=1,inplace=True)

In [64]:
# Select one day's timetable for one route or one Journey 
df_monday=df_timetable.loc[(df_timetable['week_cate']=='Workday') & (df_timetable['Journey_Pattern_ID']=='045A0001')]

In [45]:
df_monday

      Journey_Pattern_ID week_cate      Time Line_ID
98952           045A0001   Workday  06:50:00     45A
98862           045A0001   Workday  06:55:00     45A
98867           045A0001   Workday  09:30:00     45A
98958           045A0001   Workday  09:35:00     45A
99004           045A0001   Workday  09:50:00     45A
98826           045A0001   Workday  09:55:00     45A
98824           045A0001   Workday  10:00:00     45A
99006           045A0001   Workday  10:05:00     45A
98842           045A0001   Workday  10:15:00     45A
98845           045A0001   Workday  10:20:00     45A
99048           045A0001   Workday  10:25:00     45A
98846           045A0001   Workday  10:30:00     45A
98992           045A0001   Workday  11:00:00     45A
98929           045A0001   Workday  11:05:00     45A
98962           045A0001   Workday  11:50:00     45A
98872           045A0001   Workday  11:55:00     45A
98827           045A0001   Workday  12:15:00     45A
98828           045A0001   Workday  12:20:00     45A
98897           045A0001   Workday  13:20:00     45A
98896           045A0001   Workday  13:25:00     45A
98895           045A0001   Workday  13:35:00     45A
98977           045A0001   Workday  13:40:00     45A
98937           045A0001   Workday  13:50:00     45A
98938           045A0001   Workday  13:55:00     45A
98997           045A0001   Workday  14:00:00     45A
98967           045A0001   Workday  14:15:00     45A
98877           045A0001   Workday  14:20:00     45A
98879           045A0001   Workday  14:25:00     45A
99102           045A0001   Workday  14:30:00     45A
98832           045A0001   Workday  14:50:00     45A
...                  ...       ...       ...     ...
98935           045A0001   Workday  15:25:00     45A
98851           045A0001   Workday  15:30:00     45A
99052           045A0001   Workday  15:35:00     45A
98980           045A0001   Workday  18:15:00     45A
98910           045A0001   Workday  18:20:00     45A
98911           045A0001   Workday  18:25:00     45A
98947           045A0001   Workday  18:45:00     45A
98943           045A0001   Workday  18:50:00     45A
99160           045A0001   Workday  18:55:00     45A
98946           045A0001   Workday  19:00:00     45A
98882           045A0001   Workday  19:20:00     45A
98884           045A0001   Workday  19:25:00     45A
99029           045A0001   Workday  19:45:00     45A
98837           045A0001   Workday  19:50:00     45A
98836           045A0001   Workday  19:55:00     45A
98853           045A0001   Workday  20:20:00     45A
98854           045A0001   Workday  20:25:00     45A
98939           045A0001   Workday  20:30:00     45A
98852           045A0001   Workday  20:35:00     45A
98915           045A0001   Workday  21:10:00     45A
98986           045A0001   Workday  21:15:00     45A
98983           045A0001   Workday  21:20:00     45A
98916           045A0001   Workday  21:25:00     45A
98918           045A0001   Workday  21:35:00     45A
98840           045A0001   Workday  22:00:00     45A
98839           045A0001   Workday  22:05:00     45A
98949           045A0001   Workday  22:30:00     45A
98857           045A0001   Workday  22:35:00     45A
98919           045A0001   Workday  23:25:00     45A
98920           045A0001   Workday  23:30:00     45A

[63 rows x 4 columns]

In [81]:
df_timetable.to_csv('time_table.csv',index=False)

# Read Timetable and calculate the bus arriving time

In [82]:
%time df_tt= pd.read_csv('time_table.csv',dtype={ 'Journey_Pattern_ID': object})
#df_all.dtypes

CPU times: user 25.4 ms, sys: 9.56 ms, total: 34.9 ms
Wall time: 42.7 ms

In [83]:
df_tt.head(1)

  Journey_Pattern_ID  First_Stop  Last_Stop week_cate      Time Line_ID
0           00010001         226        380  Saturday  08:30:00       1

In [77]:
# Select one day's timetable for one route or one Journey 
#df_monday=df_tt.loc[(df_tt['week_cate']=='Workday') & (df_tt['Journey_Pattern_ID']=='045A0001')]

In [84]:
# Change the column name for import data to RDS 
df_tt.columns = ['journey_pattern', 'first_stop','last_stop','day_category','departure_time','line']
df_tt.to_csv('time_table.csv',index=False)

In [36]:
df_tt.dtypes

journey_pattern    object
day_category       object
departure_time     object
line               object
dtype: object

In [38]:
workday_time=[]
for index, row in df_monday.iterrows():
    begin_time=row['Time']
    workday_time.append(begin_time)
print(workday_time)

['09:00:00', '09:05:00', '09:20:00', '09:25:00', '09:40:00', '09:45:00', '10:00:00', '10:05:00', '10:15:00', '10:20:00', '10:35:00', '10:40:00', '11:00:00', '11:20:00', '11:35:00', '11:40:00', '11:55:00', '12:00:00', '12:20:00', '12:35:00', '12:40:00', '13:00:00', '13:05:00', '13:15:00', '13:20:00', '13:30:00', '13:35:00', '13:40:00', '14:00:00', '14:20:00', '14:25:00', '14:40:00', '15:00:00', '15:05:00', '15:20:00', '15:40:00', '16:00:00', '16:05:00', '16:20:00', '16:40:00', '17:20:00', '17:25:00', '17:40:00', '17:45:00', '17:55:00', '18:00:00', '18:05:00', '18:20:00', '18:25:00', '18:30:00', '18:40:00', '18:50:00', '19:00:00', '19:25:00', '19:30:00', '19:55:00', '20:00:00', '20:05:00', '20:30:00', '20:35:00', '21:00:00', '21:25:00', '21:30:00', '21:55:00', '22:00:00', '22:30:00', '22:55:00', '23:00:00']

In [39]:
# Use datetime package to calulate time 
from datetime import datetime
from datetime import timedelta

travel_time=timedelta(hours=0, minutes=30, seconds=0)

begin_time=datetime.strptime('10:35:00','%H:%M:%S')

bus_time=[]
for i in workday_time:
# Parse the time strings
    i = datetime.strptime(i,'%H:%M:%S')
    i+=travel_time
    if i>begin_time:
        bus_time.append(i)
        


print(bus_time)

First_bus=min(bus_time)

#First_bus=First_bus.time()
#print("The first bus will arrive at ",First_bus)

[datetime.datetime(1900, 1, 1, 10, 45), datetime.datetime(1900, 1, 1, 10, 50), datetime.datetime(1900, 1, 1, 11, 5), datetime.datetime(1900, 1, 1, 11, 10), datetime.datetime(1900, 1, 1, 11, 30), datetime.datetime(1900, 1, 1, 11, 50), datetime.datetime(1900, 1, 1, 12, 5), datetime.datetime(1900, 1, 1, 12, 10), datetime.datetime(1900, 1, 1, 12, 25), datetime.datetime(1900, 1, 1, 12, 30), datetime.datetime(1900, 1, 1, 12, 50), datetime.datetime(1900, 1, 1, 13, 5), datetime.datetime(1900, 1, 1, 13, 10), datetime.datetime(1900, 1, 1, 13, 30), datetime.datetime(1900, 1, 1, 13, 35), datetime.datetime(1900, 1, 1, 13, 45), datetime.datetime(1900, 1, 1, 13, 50), datetime.datetime(1900, 1, 1, 14, 0), datetime.datetime(1900, 1, 1, 14, 5), datetime.datetime(1900, 1, 1, 14, 10), datetime.datetime(1900, 1, 1, 14, 30), datetime.datetime(1900, 1, 1, 14, 50), datetime.datetime(1900, 1, 1, 14, 55), datetime.datetime(1900, 1, 1, 15, 10), datetime.datetime(1900, 1, 1, 15, 30), datetime.datetime(1900, 1, 1, 15, 35), datetime.datetime(1900, 1, 1, 15, 50), datetime.datetime(1900, 1, 1, 16, 10), datetime.datetime(1900, 1, 1, 16, 30), datetime.datetime(1900, 1, 1, 16, 35), datetime.datetime(1900, 1, 1, 16, 50), datetime.datetime(1900, 1, 1, 17, 10), datetime.datetime(1900, 1, 1, 17, 50), datetime.datetime(1900, 1, 1, 17, 55), datetime.datetime(1900, 1, 1, 18, 10), datetime.datetime(1900, 1, 1, 18, 15), datetime.datetime(1900, 1, 1, 18, 25), datetime.datetime(1900, 1, 1, 18, 30), datetime.datetime(1900, 1, 1, 18, 35), datetime.datetime(1900, 1, 1, 18, 50), datetime.datetime(1900, 1, 1, 18, 55), datetime.datetime(1900, 1, 1, 19, 0), datetime.datetime(1900, 1, 1, 19, 10), datetime.datetime(1900, 1, 1, 19, 20), datetime.datetime(1900, 1, 1, 19, 30), datetime.datetime(1900, 1, 1, 19, 55), datetime.datetime(1900, 1, 1, 20, 0), datetime.datetime(1900, 1, 1, 20, 25), datetime.datetime(1900, 1, 1, 20, 30), datetime.datetime(1900, 1, 1, 20, 35), datetime.datetime(1900, 1, 1, 21, 0), datetime.datetime(1900, 1, 1, 21, 5), datetime.datetime(1900, 1, 1, 21, 30), datetime.datetime(1900, 1, 1, 21, 55), datetime.datetime(1900, 1, 1, 22, 0), datetime.datetime(1900, 1, 1, 22, 25), datetime.datetime(1900, 1, 1, 22, 30), datetime.datetime(1900, 1, 1, 23, 0), datetime.datetime(1900, 1, 1, 23, 25), datetime.datetime(1900, 1, 1, 23, 30)]

In [40]:
First_bus=First_bus.time()
print("The first bus will arrive at ",First_bus)

The first bus will arrive at  10:45:00