## Project Dublin Bus 


## Change the data format, remove duplication and  save it

## Import package

In [1]:
#Import the required packages
#Import package pandas for data analysis
import pandas as pd

# Import package numpy for numeric computing
import numpy as np

# Import package matplotlib  for visualisation/plotting
import matplotlib.pyplot as plt

#import matplotlib.patches as mpatches
import seaborn as sns

#import package matplotlib for import plots to PDF
from matplotlib.backends.backend_pdf import PdfPages

#For showing plots directly in the notebook
#%matplotlib inline

# Reading from a csv file, into a data frame

# Read the csv file to Data Frame to do data cleaningÂ¶

In [2]:
#Change the columns's names 
Columns_name = ['Timestamp','Line_ID','Direction','Journey_Pattern_ID','Date','Vehicle_Journey_ID','Operator',
              'Congestion','Lon_WGS84','Lat_WGS84','Delay','Block_ID','Vehicle_ID','Stop_ID','At_Stop','Next_Timestamp','Between_Time','Distance_Terminal']

In [3]:
#This is one week's data in Nov 2011 
%time df = pd.read_csv('dublin_2012_week1_distance.csv',names=Columns_name, dtype={ 'Vehicle_Journey_ID': np.int64} )
df.head(3)

<string>:2: DtypeWarning: Columns (1,13) have mixed types. Specify dtype option on import or set low_memory=False.

CPU times: user 28 s, sys: 9.89 s, total: 37.9 s
Wall time: 42.1 s

,Timestamp,Line_ID,Direction,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Operator,Congestion,Lon_WGS84,Lat_WGS84,Delay,Block_ID,Vehicle_ID,Stop_ID,At_Stop,Next_Timestamp,Between_Time,Distance_Terminal
0,1352160000,15,0,00150001,2012-11-05,5826,RD,0,-6.258584,53.340099,-361,15013,33210,4870,0,1352160019,19,0.0
1,1352160000,46,0,046A1002,2012-11-05,7267,D2,0,-6.259093,53.345425,-1101,46004,36024,794,0,1352160039,39,0.0
2,1352160000,14,0,00140001,2012-11-05,6206,D2,0,-6.257329,53.287521,-126,14003,33325,1047,0,1352160019,19,0.0

In [4]:
# Check how many rows we have after loaded the csv file ((9204432, 18))
df.shape

(9204432, 18)

In [5]:
df.memory_usage(index=True).sum()

1325438288

In [6]:
#Check the features's types
df.dtypes

Timestamp               int64
Line_ID                object
Direction               int64
Journey_Pattern_ID     object
Date                   object
Vehicle_Journey_ID      int64
Operator               object
Congestion              int64
Lon_WGS84             float64
Lat_WGS84             float64
Delay                   int64
Block_ID                int64
Vehicle_ID              int64
Stop_ID                object
At_Stop                 int64
Next_Timestamp          int64
Between_Time            int64
Distance_Terminal     float64
dtype: object

In [5]:
print("The Block ID is ",pd.unique(df.Block_ID.ravel()))
%time df.groupby(['Block_ID','Journey_Pattern_ID']).size().reset_index().rename(columns={0:'count'})

The Block ID is  [ 15013  46004  14003 ..., 271069  41065  49009]
CPU times: user 1.08 s, sys: 362 ms, total: 1.44 s
Wall time: 1.48 s

      Block_ID Journey_Pattern_ID  count
0         1001           00010001   7983
1         1001           00010002   1218
2         1001           00011001   8687
3         1001           00011002   1503
4         1002           00010001   8171
5         1002           00010002    884
6         1002           00011001   9386
7         1002           00011002   1051
8         1003           00010001   8277
9         1003           00010002    391
10        1003           00011001   9361
11        1003           00011002    571
12        1004           00010001   5143
13        1004           00010002   1133
14        1004           00011001   5198
15        1004           00011002   1160
16        1005           00010001   6582
17        1005           00010002    406
18        1005           00010003    404
19        1005           00011001   7567
20        1005           00011002    659
21        1006           00010001   5168
22        1006           00010002    462
23        1006           00010003     96
24        1006           00011001   5524
25        1006           00011002    478
26        1069           00010001    140
27        1070           00011001    170
28        4001           00040001  10542
29        4001           00041001   9536
...        ...                ...    ...
3221    827002           025A0001   1446
3222    827002           025A1001    800
3223    827002           025B0001   1139
3224    827004           025A0001   1633
3225    827004           025A1001    891
3226    827005           00700001    909
3227    827005           00701001    723
3228    827005           025A1001    913
3229    827063           033X0001    983
3230    827063           033X1001   1035
3231    827065           033X0001   1137
3232    827065           033X1001   1029
3233    827066           033X0001   1401
3234    827066           033X1001   1023
3235    831035           00070003    699
3236    831235           046A1006    681
3237    831237           046A1004   1338
3238    831238           046A0007    273
3239    832002           041C1002   1926
3240    832004           01421001   1203
3241    834010           068A1001    837
3242    834012           068A1001    441
3243    834017           068A0001   1144
3244    834032           025X1002   1394
3245    834033           051X1001   1588
3246    834096           00680002    172
3247    834096           00681004    146
3248    834097           00760001    170
3249    835001           00161001   1295
3250    835002           041C1002    829

[3251 rows x 3 columns]

# Drop Some features we don't need

In [7]:
#Drop duplicate rows 
df=df.drop_duplicates()
#Drop constant column
df.drop(['Direction','Operator'],axis=1,inplace=True)

In [8]:
#Drop the features that we don't need 
df.drop(['Next_Timestamp','Between_Time'],axis=1,inplace=True)

In [9]:
#Drop Unused column
df.drop(['Line_ID','Congestion','Block_ID','Vehicle_ID'],axis=1,inplace=True)

In [10]:
#Check how many rows we deleted(Before it is  (9204432, 18))
df.shape
# The result is (9204432,10)

(9204432, 10)

In [11]:
#Show the first 5 rows.
df

,Timestamp,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Lon_WGS84,Lat_WGS84,Delay,Stop_ID,At_Stop,Distance_Terminal
0,1352160000,00150001,2012-11-05,5826,-6.258584,53.340099,-361,4870,0,0.00
1,1352160000,046A1002,2012-11-05,7267,-6.259093,53.345425,-1101,794,0,0.00
2,1352160000,00140001,2012-11-05,6206,-6.257329,53.287521,-126,1047,0,0.00
3,1352160002,041B0002,2012-11-05,61,-6.264167,53.453217,-623,3874,1,0.00
4,1352160002,039A1002,2012-11-05,3795,-6.262447,53.346767,-532,1479,0,0.00
5,1352160002,00650001,2012-11-05,4004,-6.594641,53.129776,-287,7283,0,0.00
6,1352160002,040D1001,2012-11-05,2466,-6.258850,53.362499,-488,52,0,0.00
7,1352160002,00111002,2012-11-05,5241,-6.230217,53.323002,-536,320,0,0.00
8,1352160002,00311001,2012-11-05,2819,-6.241683,53.362484,-386,613,0,0.00
9,1352160002,00270001,2012-11-05,4976,-6.290833,53.319332,0,2355,1,0.00
10,1352160002,00670001,2012-11-05,893,-6.476370,53.355328,-160,3892,0,0.00
11,1352160002,00790001,2012-11-05,3533,-6.332334,53.342850,328,2907,0,0.00
12,1352160002,00420002,2012-11-05,3880,-6.174524,53.442135,0,3579,0,0.00
13,1352160002,066A0001,2012-11-05,2940,-6.372633,53.355251,-362,3993,0,0.00
14,1352160002,00790001,2012-11-05,3511,-6.296600,53.347717,29,2907,0,0.00
15,1352160002,033B0001,2012-11-05,503,-6.141323,53.490158,61,3722,0,0.00
16,1352160002,01400001,2012-11-05,6615,-6.276083,53.343884,0,895,1,0.00
17,1352160002,00440001,2012-11-05,5009,-6.220562,53.267975,500,3467,0,0.00
18,1352160002,083A0001,2012-11-05,7099,-6.273733,53.419632,0,324,1,0.00
19,1352160002,027B1002,2012-11-05,374,-6.243900,53.398499,169,324,0,0.00
20,1352160002,00381003,2012-11-05,1243,-6.266693,53.356422,-50,818,0,0.00
21,1352160002,016C0001,2012-11-05,6175,-6.254583,53.355534,-23,270,1,0.00
22,1352160002,07470001,2012-11-05,4328,-6.253083,53.371799,0,3665,1,0.00
23,1352160002,041C0001,2012-11-05,126,-6.244452,53.450260,-464,3090,0,0.00
24,1352160002,00391001,2012-11-05,3622,-6.333664,53.372768,-310,1847,0,0.00
25,1352160002,00250001,2012-11-05,713,-6.349717,53.349232,-458,2220,0,0.00
26,1352160002,02390002,2012-11-05,1871,-6.336783,53.395100,-218,4411,0,0.00
27,1352160002,00431001,2012-11-05,3954,-6.235034,53.358368,-23,296,1,0.00
28,1352160002,01401001,2012-11-05,6612,-6.277017,53.416817,259,7149,1,0.00
29,1352160004,046A1001,2012-11-05,7417,-6.242417,53.326218,-413,804,0,0.00
...,...,...,...,...,...,...,...,...,...,...
9204402,1352764792,00610001,2012-11-12,5692,-6.232383,53.318565,191,2955,1,23369.36
9204403,1352764792,00271001,2012-11-12,4804,-6.163950,53.394917,516,4595,1,29477.82
9204404,1352764792,00830001,2012-11-12,7185,-6.341250,53.323601,-369,2492,1,26023.49
9204405,1352764792,025B0001,2012-11-12,680,-6.451833,53.344685,-188,6289,1,21743.13
9204406,1352764792,01021001,2012-11-12,435,-6.197300,53.389282,-429,4381,1,29609.89
9204407,1352764792,01450001,2012-11-12,6702,-6.202506,53.294086,2661,435,0,13487.50
9204408,1352764792,00441001,2012-11-12,5028,-6.248267,53.340366,264,207,1,32938.86
9204409,1352764792,00431001,2012-11-12,3954,-6.203300,53.360332,-9,296,1,22273.05
9204410,1352764792,039A0001,2012-11-12,3705,-6.326383,53.370384,-548,7162,1,36959.74
9204411,1352764792,00140001,2012-11-12,6206,-6.244843,53.279324,-665,2860,0,19141.47
9204412,1352764792,017A0005,2012-11-12,6160,-6.267300,53.417183,0,1012,1,32337.86
9204413,1352764792,00151001,2012-11-12,5929,-6.224300,53.409966,55,6317,1,27807.86
9204414,1352764792,077A0001,2012-11-12,4912,-6.392300,53.312782,0,7459,1,27254.02
9204415,1352764792,040D0001,2012-11-12,2460,-6.385174,53.415138,-315,4986,1,13831.98
9204416,1352764792,00690001,2012-11-12,1919,-6.479683,53.277718,48,4564,0,0.00
9204417,1352764792,040D1001,2012-11-12,2466,-6.261066,53.360016,-429,6071,1,17232.70
9204418,1352764792,00011001,2012-11-12,5186,-6.262190,53.391178,0,226,0,0.00
9204419,1352764792,00140001,2012-11-12,6285,-6.256783,53.354065,0,6044,1,29113.05
9204420,1352764792,00381003,2012-11-12,1243,-6.261583,53.352734,-188,265,1,17614.83
9204421,1352764792,00760001,2012-11-12,4553,-6.369298,53.294262,1,2620,0,11559.67
9204422,1352764792,00371002,2012-11-12,2115,-6.260700,53.347198,-249,313,1,15676.00
9204423,1352764792,046A0001,2012-11-12,7345,-6.231650,53.318817,0,2039,1,27763.72
9204424,1352764796,00310003,2012-11-12,2843,-6.065545,53.387112,0,559,0,14468.80
9204425,1352764796,00161001,2012-11-12,5652,-6.218033,53.425232,-488,7347,1,26266.56
9204426,1352764796,01451002,2012-11-12,6796,-6.256326,53.338795,-817,786,0,24420.28
9204427,1352764796,01020001,2012-11-12,415,-6.250725,53.439415,-564,815,0,19959.37
9204428,1352764796,00331005,2012-11-12,269,-6.109184,53.580326,-36,3818,0,7483.98
9204429,1352764796,00380001,2012-11-12,1269,-6.375340,53.399990,154,1819,0,16435.03
9204430,1352764798,015A0001,2012-11-12,3130,-6.299134,53.311970,267,1089,0,8033.41
9204431,1352764798,00070001,2012-11-12,6963,-6.138767,53.276184,-128,2040,1,12272.62

# Do more cleaning for the data frame

In [12]:
df_groupby=df.groupby(['Vehicle_Journey_ID','Date','Journey_Pattern_ID'])

#size = df_groupby.size()
#size=size[size<13]

#keys=df_groupby.groups

In [13]:
# Filter all the data only have less than 13 rows data 
df_short_Journ=df_groupby.filter(lambda x: len(x) < 13)

In [14]:
# Drop all the Journery that are less than a number 

df=pd.concat([df, df_short_Journ]).drop_duplicates(keep=False)

In [15]:
#Check how many rows we deleted(Before it is(9204432, 10)
df.shape
# The result now is (9166233, 10)

(9166233, 10)

In [16]:
%time df.groupby(['Vehicle_Journey_ID','Journey_Pattern_ID','Date']).size().reset_index().rename(columns={0:'count'})

CPU times: user 1.73 s, sys: 433 ms, total: 2.17 s
Wall time: 2.25 s

       Vehicle_Journey_ID Journey_Pattern_ID        Date  count
0                       1           033A1002  2012-11-06    169
1                       1           033A1002  2012-11-07    157
2                       1           033A1002  2012-11-08    124
3                       1           033A1002  2012-11-09    147
4                       1           033A1002  2012-11-12    150
5                       2           033A0001  2012-11-06    162
6                       2           033A0001  2012-11-07    196
7                       2           033A0001  2012-11-08    147
8                       2           033A0001  2012-11-09    218
9                       2           033A0001  2012-11-12    207
10                      4           00411001  2012-11-06    178
11                      4           00411001  2012-11-07    175
12                      4           00411001  2012-11-08    180
13                      4           00411001  2012-11-09    180
14                      4           00411001  2012-11-12    182
15                      5           041C0001  2012-11-06    175
16                      5           041C0001  2012-11-07    165
17                      5           041C0001  2012-11-08    164
18                      5           041C0001  2012-11-09    159
19                      5           041C0001  2012-11-12    168
20                      6           00411002  2012-11-06    189
21                      6           00411002  2012-11-07    178
22                      6           00411002  2012-11-08    207
23                      6           00411002  2012-11-09    190
24                      6           00411002  2012-11-12    217
25                      7           00410001  2012-11-06     61
26                      7           00410001  2012-11-07     68
27                      7           00410001  2012-11-08     63
28                      7           00410001  2012-11-09     59
29                      7           00410001  2012-11-12     60
...                   ...                ...         ...    ...
46636              990180           00071001  2012-11-08    200
46637              990394           039A0002  2012-11-07    151
46638              990640           00041001  2012-11-09     26
46639              990706           00411001  2012-11-09    284
46640              990711           00271001  2012-11-11     33
46641              990905           00311001  2012-11-06    125
46642              990912           077A1001  2012-11-07    227
46643              991252           00091001  2012-11-12     16
46644              991654           00041001  2012-11-09     44
46645              992606           025A0001  2012-11-12    255
46646              992714           046A1001  2012-11-12    267
46647              993235           00161001  2012-11-09    256
46648              993374           00390001  2012-11-07    344
46649              993439           00071002  2012-11-09     26
46650              993669           029A1001  2012-11-07    128
46651              994052           039A0002  2012-11-09    102
46652              994351           00380001  2012-11-12    192
46653              994364           00071001  2012-11-12     26
46654              994421           025A1001  2012-11-08    217
46655              995509           025A1001  2012-11-09    422
46656              995782           00750001  2012-11-09     24
46657              996115           00171001  2012-11-06    167
46658              996128           01501001  2012-11-06     13
46659              996843           00131002  2012-11-07    405
46660              997891           00131002  2012-11-09     22
46661              998471           00011001  2012-11-10    170
46662              998547           077A0001  2012-11-09    221
46663              998685           00071001  2012-11-08     35
46664              999390           077A0001  2012-11-06    188
46665              999825           046A0001  2012-11-12    250

[46666 rows x 4 columns]

In [17]:
# Only keep the first row for every trip at the same Stop(keep both at or not_at stop)
df = df.drop_duplicates(['Vehicle_Journey_ID','Journey_Pattern_ID','Date','Stop_ID','At_Stop'])

In [18]:
# Check how many rows are deleted before it is (9134097, 13)
df.shape 
# The result now is (3175832, 10)

(3175832, 10)

# Add new features for the data frame

In [19]:
#Convert Timestamp to datetime and new column datetime to data frame 
df['datetime'] = pd.to_datetime(df['Timestamp'],unit='s')
df.head(5)

,Timestamp,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Lon_WGS84,Lat_WGS84,Delay,Stop_ID,At_Stop,Distance_Terminal,datetime
0,1352160000,00150001,2012-11-05,5826,-6.258584,53.340099,-361,4870,0,0.0,2012-11-06 00:00:00
1,1352160000,046A1002,2012-11-05,7267,-6.259093,53.345425,-1101,794,0,0.0,2012-11-06 00:00:00
2,1352160000,00140001,2012-11-05,6206,-6.257329,53.287521,-126,1047,0,0.0,2012-11-06 00:00:00
3,1352160002,041B0002,2012-11-05,61,-6.264167,53.453217,-623,3874,1,0.0,2012-11-06 00:00:02
4,1352160002,039A1002,2012-11-05,3795,-6.262447,53.346767,-532,1479,0,0.0,2012-11-06 00:00:02

In [20]:
#ADD day of the week to the date frame 
df['day_of_week'] = df['datetime'].dt.weekday_name
df.head(3)

,Timestamp,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Lon_WGS84,Lat_WGS84,Delay,Stop_ID,At_Stop,Distance_Terminal,datetime,day_of_week
0,1352160000,00150001,2012-11-05,5826,-6.258584,53.340099,-361,4870,0,0.0,2012-11-06,Tuesday
1,1352160000,046A1002,2012-11-05,7267,-6.259093,53.345425,-1101,794,0,0.0,2012-11-06,Tuesday
2,1352160000,00140001,2012-11-05,6206,-6.257329,53.287521,-126,1047,0,0.0,2012-11-06,Tuesday

In [21]:
# Add new feature Trip_Time 
zscore=lambda x: (x - x.min())
df['Trip_Time']= df.groupby(['Vehicle_Journey_ID','Journey_Pattern_ID','Date'])['Timestamp'].transform(zscore)

In [22]:
#Change date column type for the convertion to day of week 
#df['Date'] = pd.to_datetime(df['Date'])
#pd.to_datetime(df['Date'], format="%m/%d/%Y")
df.dtypes

Timestamp                      int64
Journey_Pattern_ID            object
Date                          object
Vehicle_Journey_ID             int64
Lon_WGS84                    float64
Lat_WGS84                    float64
Delay                          int64
Stop_ID                       object
At_Stop                        int64
Distance_Terminal            float64
datetime              datetime64[ns]
day_of_week                   object
Trip_Time                      int64
dtype: object

# Descibe  categorical_columns and continuous_columns features

In [23]:
# Select columns containing categorical data
categorical_columns = df[['Journey_Pattern_ID','Vehicle_Journey_ID','Stop_ID','At_Stop','day_of_week']].columns

# Convert data type to category for these columns
for column in categorical_columns:
    df[column] = df[column].astype('category')
# Descriptive stats for categorical features
#df.select_dtypes(['category']).describe().T
df[categorical_columns].describe().T

                      count unique       top     freq
Journey_Pattern_ID  3175832    471  046A1001    63929
Vehicle_Journey_ID  3175832  17400      4746      733
Stop_ID             3175832   9415       794     7851
At_Stop             3175832      2         0  2293236
day_of_week         3175832      7  Thursday   514592

In [24]:
#Find all the continuous features 

continuous_columns=df[['Lon_WGS84','Lat_WGS84','Delay','Distance_Terminal','Trip_Time']].columns

# Descriptive stats for continuous features
df[continuous_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Lon_WGS84,3175832.0,-6.270168,0.081187,-6.615067,-6.309352,-6.264491,-6.228236,-6.053133
Lat_WGS84,3175832.0,53.343526,0.053041,53.070332,53.318550,53.345066,53.372845,53.606518
Delay,3175832.0,54.270437,423.123157,-8958.000000,-153.000000,14.000000,227.000000,15188.000000
Distance_Terminal,3175832.0,10604.740563,7497.188347,0.000000,4695.230000,9485.595000,15468.260000,198057.590000
Trip_Time,3175832.0,2131.065564,1921.173023,0.000000,958.000000,1838.000000,2995.000000,62532.000000

## The Max trip time is too long, so we need to check that

In [25]:
df_max_time=df.loc[df['Trip_Time']==62532]
df_max_time

,Timestamp,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Lon_WGS84,Lat_WGS84,Delay,Stop_ID,At_Stop,Distance_Terminal,datetime,day_of_week,Trip_Time
5976689,1352504677,00390001,2012-11-09,3625,-6.430337,53.390549,0,7162,0,26605.59,2012-11-09 23:44:37,Friday,62532

In [38]:
# Get the max time Jour and check the issue 
df_max_time_Journery=df.loc[(df['Vehicle_Journey_ID']==2084) & (df['day_of_week']=='Friday')]

In [39]:
#Show the error of the Jour 
df_max_time_Journery

,Timestamp,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Lon_WGS84,Lat_WGS84,Delay,Stop_ID,At_Stop,Distance_Terminal,datetime,day_of_week,Trip_Time
5544493,1352482849,00380001,2012-11-09,2084,-6.421067,53.420315,0,4745,1,0.00,2012-11-09 17:40:49,Friday,0
5545068,1352482867,00381002,2012-11-09,2084,-6.421067,53.420315,0,4745,1,0.00,2012-11-09 17:41:07,Friday,0
5545774,1352482888,00381002,2012-11-09,2084,-6.421067,53.420315,0,4745,1,0.00,2012-11-09 17:41:28,Friday,21
5546473,1352482908,00381002,2012-11-09,2084,-6.421067,53.420315,0,4745,1,0.00,2012-11-09 17:41:48,Friday,41
5547427,1352482930,00381002,2012-11-09,2084,-6.421067,53.420315,0,4745,1,0.00,2012-11-09 17:42:10,Friday,63
5548709,1352482968,00381002,2012-11-09,2084,-6.421067,53.420315,0,4745,1,0.00,2012-11-09 17:42:48,Friday,101
5549458,1352482989,00381002,2012-11-09,2084,-6.421067,53.420315,0,4745,1,0.00,2012-11-09 17:43:09,Friday,122
5549797,1352483008,00381002,2012-11-09,2084,-6.421067,53.420315,0,4745,1,0.00,2012-11-09 17:43:28,Friday,141
5550538,1352483028,00381002,2012-11-09,2084,-6.421067,53.420315,0,4745,1,0.00,2012-11-09 17:43:48,Friday,161
5551364,1352483050,00381002,2012-11-09,2084,-6.421067,53.420315,0,4745,1,0.00,2012-11-09 17:44:10,Friday,183
5552130,1352483073,00381002,2012-11-09,2084,-6.421067,53.420315,0,4745,1,0.00,2012-11-09 17:44:33,Friday,206
5552863,1352483092,00381002,2012-11-09,2084,-6.421067,53.420315,0,4745,1,0.00,2012-11-09 17:44:52,Friday,225
5553580,1352483115,00381002,2012-11-09,2084,-6.421067,53.420315,0,4745,1,0.00,2012-11-09 17:45:15,Friday,248
5553983,1352483129,00381002,2012-11-09,2084,-6.418790,53.420422,-37,4745,0,151.85,2012-11-09 17:45:29,Friday,262
5554279,1352483134,00381002,2012-11-09,2084,-6.419248,53.420460,-37,4745,0,182.59,2012-11-09 17:45:34,Friday,267
5554587,1352483148,00381002,2012-11-09,2084,-6.417768,53.419384,-37,4745,0,337.58,2012-11-09 17:45:48,Friday,281
5556235,1352483195,00381002,2012-11-09,2084,-6.421127,53.415569,-37,4989,0,817.32,2012-11-09 17:46:35,Friday,328
5556869,1352483209,00381002,2012-11-09,2084,-6.422191,53.414593,-37,4989,0,946.95,2012-11-09 17:46:49,Friday,342
5557545,1352483229,00381002,2012-11-09,2084,-6.424434,53.412567,-37,4989,0,1217.30,2012-11-09 17:47:09,Friday,362
5558239,1352483254,00381002,2012-11-09,2084,-6.423022,53.411663,-37,4989,0,1354.92,2012-11-09 17:47:34,Friday,387
5558903,1352483273,00381002,2012-11-09,2084,-6.417724,53.410603,-58,4991,0,1726.45,2012-11-09 17:47:53,Friday,406
5559619,1352483288,00381002,2012-11-09,2084,-6.412752,53.409843,-58,4992,0,2067.73,2012-11-09 17:48:08,Friday,421
5560226,1352483312,00381002,2012-11-09,2084,-6.409494,53.409027,-74,4992,0,2302.65,2012-11-09 17:48:32,Friday,445
5560975,1352483327,00381002,2012-11-09,2084,-6.408249,53.408810,-74,1719,1,2388.89,2012-11-09 17:48:47,Friday,460
5561500,1352483351,00381002,2012-11-09,2084,-6.408249,53.408810,-42,1719,1,2388.89,2012-11-09 17:49:11,Friday,484
5562362,1352483370,00381002,2012-11-09,2084,-6.405205,53.408314,-42,1719,0,2598.71,2012-11-09 17:49:30,Friday,503
5562875,1352483391,00381002,2012-11-09,2084,-6.400676,53.407543,-42,1719,0,2911.89,2012-11-09 17:49:51,Friday,524
5563737,1352483415,00381002,2012-11-09,2084,-6.398216,53.406956,-42,1719,0,3088.05,2012-11-09 17:50:15,Friday,548
5564398,1352483429,00381002,2012-11-09,2084,-6.395821,53.406284,-42,1828,0,3264.01,2012-11-09 17:50:29,Friday,562
5564791,1352483450,00381002,2012-11-09,2084,-6.394598,53.405769,-42,1829,0,3363.51,2012-11-09 17:50:50,Friday,583
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5780025,1352491283,00381002,2012-11-09,2084,-6.278650,53.416698,548,6059,0,50716.90,2012-11-09 20:01:23,Friday,8416
5780795,1352491328,00381002,2012-11-09,2084,-6.278650,53.416698,548,6059,0,50716.90,2012-11-09 20:02:08,Friday,8461
5781158,1352491346,00381002,2012-11-09,2084,-6.278650,53.416698,548,6059,0,50716.90,2012-11-09 20:02:26,Friday,8479
5781552,1352491365,00381002,2012-11-09,2084,-6.278633,53.416698,548,6059,0,50718.03,2012-11-09 20:02:45,Friday,8498
5782054,1352491387,00381002,2012-11-09,2084,-6.278650,53.416698,548,6059,0,50719.16,2012-11-09 20:03:07,Friday,8520
5782408,1352491406,00381002,2012-11-09,2084,-6.278666,53.416698,548,6059,0,50720.22,2012-11-09 20:03:26,Friday,8539
5782890,1352491426,00381002,2012-11-09,2084,-6.278666,53.416718,548,6059,0,50722.45,2012-11-09 20:03:46,Friday,8559
5783265,1352491448,00381002,2012-11-09,2084,-6.278650,53.416718,548,6059,0,50723.51,2012-11-09 20:04:08,Friday,8581
5783667,1352491467,00381002,2012-11-09,2084,-6.278650,53.416718,548,6059,0,50723.51,2012-11-09 20:04:27,Friday,8600
5784087,1352491485,00381002,2012-11-09,2084,-6.278650,53.416718,548,6059,0,50723.51,2012-11-09 20:04:45,Friday,8618
5784524,1352491508,00381002,2012-11-09,2084,-6.278650,53.416718,548,6059,0,50723.51,2012-11-09 20:05:08,Friday,8641
5784871,1352491526,00381002,2012-11-09,2084,-6.278633,53.416718,548,6059,0,50724.64,2012-11-09 20:05:26,Friday,8659
5785310,1352491547,00381002,2012-11-09,2084,-6.278633,53.416718,548,6059,0,50724.64,2012-11-09 20:05:47,Friday,8680
5785647,1352491565,00381002,2012-11-09,2084,-6.278633,53.416718,548,6059,0,50724.64,2012-11-09 20:06:05,Friday,8698
5786092,1352491585,00381002,2012-11-09,2084,-6.278650,53.416718,548,6059,0,50725.77,2012-11-09 20:06:25,Friday,8718
5786507,1352491606,00381002,2012-11-09,2084,-6.278650,53.416718,548,6059,0,50725.77,2012-11-09 20:06:46,Friday,8739
5786915,1352491626,00381002,2012-11-09,2084,-6.278650,53.416718,548,6059,0,50725.77,2012-11-09 20:07:06,Friday,8759
5787311,1352491645,00381002,2012-11-09,2084,-6.278650,53.416718,548,6059,0,50725.77,2012-11-09 20:07:25,Friday,8778
5787805,1352491667,00381002,2012-11-09,2084,-6.278666,53.416718,548,6059,0,50726.83,2012-11-09 20:07:47,Friday,8800
5788116,1352491685,00381002,2012-11-09,2084,-6.278666,53.416718,548,6059,0,50726.83,2012-11-09 20:08:05,Friday,8818
5788535,1352491706,00381002,2012-11-09,2084,-6.278666,53.416733,548,6059,0,50728.50,2012-11-09 20:08:26,Friday,8839
5788993,1352491726,00381002,2012-11-09,2084,-6.278650,53.416718,548,6059,0,50730.48,2012-11-09 20:08:46,Friday,8859
5789221,1352491746,00381002,2012-11-09,2084,-6.278650,53.416698,548,6059,0,50732.71,2012-11-09 20:09:06,Friday,8879
5789907,1352491768,00381002,2012-11-09,2084,-6.278633,53.416718,548,6059,0,50735.21,2012-11-09 20:09:28,Friday,8901
5790156,1352491784,00381002,2012-11-09,2084,-6.278650,53.416718,548,6059,0,50736.34,2012-11-09 20:09:44,Friday,8917
5790549,1352491805,00381002,2012-11-09,2084,-6.278633,53.416718,548,6059,0,50737.47,2012-11-09 20:10:05,Friday,8938
5790970,1352491825,00381002,2012-11-09,2084,-6.278650,53.416718,548,6059,0,50738.60,2012-11-09 20:10:25,Friday,8958
5791389,1352491846,00381002,2012-11-09,2084,-6.278650,53.416718,548,6059,0,50738.60,2012-11-09 20:10:46,Friday,8979
5791764,1352491866,00381002,2012-11-09,2084,-6.278650,53.416718,548,6059,0,50738.60,2012-11-09 20:11:06,Friday,8999
5891706,1352498070,00370001,2012-11-09,2084,-6.392183,53.394115,0,4747,0,0.00,2012-11-09 21:54:30,Friday,0

# Solution for the error is to remove all the trip time is more than 3 hours

In [26]:
# Drop all the rows' Trip_Time is longer than 3 hours 
df=df.drop(df.index[df['Trip_Time']>=10800])

In [27]:
#Check how many rows we deleted(Before it is (3175832, 10)
df.shape

(3169731, 13)

In [28]:
# Check the result after the 
df[continuous_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Lon_WGS84,3169731.0,-6.270168,0.081152,-6.615067,-6.309314,-6.264495,-6.228252,-6.053133
Lat_WGS84,3169731.0,53.343494,0.053058,53.070332,53.318523,53.345020,53.372772,53.606518
Delay,3169731.0,54.072913,421.422407,-8958.000000,-153.000000,13.000000,227.000000,15188.000000
Distance_Terminal,3169731.0,10585.628070,7476.727585,0.000000,4686.710000,9470.000000,15448.840000,198057.590000
Trip_Time,3169731.0,2077.140856,1400.227907,0.000000,958.000000,1834.000000,2983.000000,10792.000000

In [29]:
# Check the max trip time again 
df_max_time=df.loc[df['Trip_Time']==10792]
df_max_time

,Timestamp,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Lon_WGS84,Lat_WGS84,Delay,Stop_ID,At_Stop,Distance_Terminal,datetime,day_of_week,Trip_Time
5546011,1352482888,029A1001,2012-11-09,2651,-6.257817,53.349602,331,291,0,11041.32,2012-11-09 17:41:28,Friday,10792

In [30]:
# Get the max time Jour and check the issue 
df_max_time_Journery=df.loc[(df['Vehicle_Journey_ID']==2651) & (df['day_of_week']=='Friday')]

In [31]:
# Check the max Jour
df_max_time_Journery

,Timestamp,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Lon_WGS84,Lat_WGS84,Delay,Stop_ID,At_Stop,Distance_Terminal,datetime,day_of_week,Trip_Time
5245399,1352472096,029A1001,2012-11-09,2651,-6.167767,53.400734,0,738,1,0.00,2012-11-09 14:41:36,Friday,0
5250133,1352472296,029A1001,2012-11-09,2651,-6.161946,53.397556,-7,738,0,1407.28,2012-11-09 14:44:56,Friday,200
5252533,1352472396,029A1001,2012-11-09,2651,-6.163486,53.395214,34,739,1,1690.81,2012-11-09 14:46:36,Friday,300
5253496,1352472435,029A1001,2012-11-09,2651,-6.165071,53.394524,54,739,0,1821.25,2012-11-09 14:47:15,Friday,339
5253934,1352472456,029A1001,2012-11-09,2651,-6.167269,53.392765,-1,740,0,2065.60,2012-11-09 14:47:36,Friday,360
5256825,1352472579,029A1001,2012-11-09,2651,-6.167566,53.391720,89,741,0,2183.74,2012-11-09 14:49:39,Friday,483
5259627,1352472695,029A1001,2012-11-09,2651,-6.169862,53.389839,148,742,0,2454.66,2012-11-09 14:51:35,Friday,599
5260617,1352472736,029A1001,2012-11-09,2651,-6.172738,53.388058,117,743,1,2730.16,2012-11-09 14:52:16,Friday,640
5261082,1352472757,029A1001,2012-11-09,2651,-6.174412,53.386803,117,743,0,2908.80,2012-11-09 14:52:37,Friday,661
5261556,1352472777,029A1001,2012-11-09,2651,-6.174950,53.385303,91,744,1,3079.54,2012-11-09 14:52:57,Friday,681
5262045,1352472795,029A1001,2012-11-09,2651,-6.175487,53.384388,91,744,0,3187.46,2012-11-09 14:53:15,Friday,699
5263481,1352472857,029A1001,2012-11-09,2651,-6.175656,53.381210,74,745,1,3553.44,2012-11-09 14:54:17,Friday,761
5264408,1352472896,029A1001,2012-11-09,2651,-6.175455,53.380894,94,745,0,3591.07,2012-11-09 14:54:56,Friday,800
5267210,1352473017,029A1001,2012-11-09,2651,-6.176209,53.380276,183,600,1,3726.80,2012-11-09 14:56:57,Friday,921
5267703,1352473035,029A1001,2012-11-09,2651,-6.176963,53.380192,199,600,0,3777.84,2012-11-09 14:57:15,Friday,939
5270570,1352473156,029A1001,2012-11-09,2651,-6.176580,53.379082,268,654,0,4013.04,2012-11-09 14:59:16,Friday,1060
5272006,1352473215,029A1001,2012-11-09,2651,-6.175414,53.377735,268,655,1,4232.01,2012-11-09 15:00:15,Friday,1119
5272473,1352473236,029A1001,2012-11-09,2651,-6.176629,53.377064,268,655,0,4342.08,2012-11-09 15:00:36,Friday,1140
5272964,1352473256,029A1001,2012-11-09,2651,-6.177691,53.376472,268,656,1,4438.70,2012-11-09 15:00:56,Friday,1160
5273923,1352473295,029A1001,2012-11-09,2651,-6.179069,53.375729,268,656,0,4562.18,2012-11-09 15:01:35,Friday,1199
5274423,1352473315,029A1001,2012-11-09,2651,-6.181062,53.375198,248,657,0,4707.39,2012-11-09 15:01:55,Friday,1219
5274953,1352473338,029A1001,2012-11-09,2651,-6.183123,53.375053,248,658,1,4845.50,2012-11-09 15:02:18,Friday,1242
5275389,1352473356,029A1001,2012-11-09,2651,-6.185264,53.375229,223,658,0,4989.33,2012-11-09 15:02:36,Friday,1260
5275851,1352473375,029A1001,2012-11-09,2651,-6.188602,53.375759,194,659,0,5219.18,2012-11-09 15:02:55,Friday,1279
5276840,1352473416,029A1001,2012-11-09,2651,-6.194147,53.375576,138,605,0,5628.87,2012-11-09 15:03:36,Friday,1320
5277829,1352473457,029A1001,2012-11-09,2651,-6.201602,53.372978,12,606,0,6209.56,2012-11-09 15:04:17,Friday,1361
5278280,1352473475,029A1001,2012-11-09,2651,-6.202461,53.371899,12,607,0,6342.56,2012-11-09 15:04:35,Friday,1379
5280190,1352473556,029A1001,2012-11-09,2651,-6.204123,53.371151,54,608,1,6492.13,2012-11-09 15:05:56,Friday,1460
5280694,1352473577,029A1001,2012-11-09,2651,-6.204828,53.371078,69,608,0,6539.75,2012-11-09 15:06:17,Friday,1481
5281594,1352473615,029A1001,2012-11-09,2651,-6.208631,53.369884,69,609,1,6825.64,2012-11-09 15:06:55,Friday,1519
5282110,1352473636,029A1001,2012-11-09,2651,-6.208801,53.369793,98,609,0,6840.83,2012-11-09 15:07:16,Friday,1540
5283017,1352473679,029A1001,2012-11-09,2651,-6.212245,53.368126,98,610,0,7135.85,2012-11-09 15:07:59,Friday,1583
5284477,1352473738,029A1001,2012-11-09,2651,-6.222342,53.366535,71,611,0,7830.90,2012-11-09 15:08:58,Friday,1642
5285385,1352473775,029A1001,2012-11-09,2651,-6.224755,53.365566,71,612,0,8024.46,2012-11-09 15:09:35,Friday,1679
5285849,1352473797,029A1001,2012-11-09,2651,-6.227307,53.364452,71,613,0,8234.77,2012-11-09 15:09:57,Friday,1701
5289703,1352473955,029A1001,2012-11-09,2651,-6.233564,53.363689,166,614,1,8665.14,2012-11-09 15:12:35,Friday,1859
5290150,1352473975,029A1001,2012-11-09,2651,-6.234828,53.363319,166,614,0,8758.82,2012-11-09 15:12:55,Friday,1879
5290684,1352473996,029A1001,2012-11-09,2651,-6.237561,53.361809,125,615,0,9006.50,2012-11-09 15:13:16,Friday,1900
5293060,1352474098,029A1001,2012-11-09,2651,-6.241836,53.358131,144,616,0,9505.08,2012-11-09 15:14:58,Friday,2002
5293597,1352474117,029A1001,2012-11-09,2651,-6.244293,53.356518,144,617,0,9747.95,2012-11-09 15:15:17,Friday,2021
5294043,1352474135,029A1001,2012-11-09,2651,-6.244881,53.356121,144,618,0,9806.98,2012-11-09 15:15:35,Friday,2039
5296476,1352474237,029A1001,2012-11-09,2651,-6.248475,53.353065,204,619,0,10223.20,2012-11-09 15:17:17,Friday,2141
5297960,1352474296,029A1001,2012-11-09,2651,-6.249868,53.351669,204,675,0,10404.15,2012-11-09 15:18:16,Friday,2200
5299045,1352474343,029A1001,2012-11-09,2651,-6.251528,53.351185,204,620,0,10527.12,2012-11-09 15:19:03,Friday,2247
5300041,1352474384,029A1001,2012-11-09,2651,-6.251458,53.351196,243,620,1,10531.94,2012-11-09 15:19:44,Friday,2288
5303495,1352474525,029A1001,2012-11-09,2651,-6.256236,53.350414,256,621,1,10861.85,2012-11-09 15:22:05,Friday,2429
5303995,1352474543,029A1001,2012-11-09,2651,-6.257779,53.350166,256,621,0,10968.24,2012-11-09 15:22:23,Friday,2447
5546011,1352482888,029A1001,2012-11-09,2651,-6.257817,53.349602,331,291,0,11041.32,2012-11-09 17:41:28,Friday,10792

# Save the data for next step

In [32]:
#Save the Dataframe to CSV file for next step
df.to_csv('Dublin_2012_Step2.csv')

# Check the most frequently Vehicle_Journey_ID

In [41]:
# Find the most frequently Vehicle_Journey_ID is 221 from table before 
df_most=df.loc[df.Vehicle_Journey_ID==221]

In [42]:
df_most

,Timestamp,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Lon_WGS84,Lat_WGS84,Delay,Stop_ID,At_Stop,Distance_Terminal,datetime,day_of_week,Trip_Time
198776,1352190892,00331001,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:34:52,Tuesday,0
199468,1352190910,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:35:10,Tuesday,0
199966,1352190929,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:35:29,Tuesday,19
200815,1352190949,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:35:49,Tuesday,39
201515,1352190970,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:36:10,Tuesday,60
202174,1352190990,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:36:30,Tuesday,80
202844,1352191013,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:36:53,Tuesday,103
203598,1352191029,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:37:09,Tuesday,119
204212,1352191050,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:37:30,Tuesday,140
205024,1352191071,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:37:51,Tuesday,161
205684,1352191089,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:38:09,Tuesday,179
206380,1352191109,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:38:29,Tuesday,199
206925,1352191128,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:38:48,Tuesday,218
207725,1352191151,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:39:11,Tuesday,241
208557,1352191171,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:39:31,Tuesday,261
209166,1352191190,00330002,2012-11-06,221,-6.255883,53.349083,0,292,1,0.00,2012-11-06 08:39:50,Tuesday,280
209854,1352191208,00330002,2012-11-06,221,-6.255883,53.349083,7,292,1,0.00,2012-11-06 08:40:08,Tuesday,298
210461,1352191229,00330002,2012-11-06,221,-6.255883,53.349083,27,292,1,0.00,2012-11-06 08:40:29,Tuesday,319
211235,1352191249,00330002,2012-11-06,221,-6.255883,53.349083,47,292,1,0.00,2012-11-06 08:40:49,Tuesday,339
211970,1352191270,00330002,2012-11-06,221,-6.255883,53.349083,67,292,1,0.00,2012-11-06 08:41:10,Tuesday,360
212634,1352191288,00330002,2012-11-06,221,-6.255883,53.349083,87,292,1,0.00,2012-11-06 08:41:28,Tuesday,378
213324,1352191309,00330002,2012-11-06,221,-6.255165,53.349129,106,292,0,48.09,2012-11-06 08:41:49,Tuesday,399
213957,1352191329,00330002,2012-11-06,221,-6.255105,53.349136,125,292,0,52.16,2012-11-06 08:42:09,Tuesday,419
214719,1352191350,00330002,2012-11-06,221,-6.255105,53.349136,145,292,0,52.16,2012-11-06 08:42:30,Tuesday,440
216127,1352191389,00330002,2012-11-06,221,-6.255105,53.349136,185,292,0,52.16,2012-11-06 08:43:09,Tuesday,479
216709,1352191409,00330002,2012-11-06,221,-6.255105,53.349136,205,292,0,52.16,2012-11-06 08:43:29,Tuesday,499
217532,1352191430,00330002,2012-11-06,221,-6.253914,53.349510,205,292,0,141.73,2012-11-06 08:43:50,Tuesday,520
218176,1352191449,00330002,2012-11-06,221,-6.253752,53.349636,225,292,0,159.42,2012-11-06 08:44:09,Tuesday,539
218892,1352191469,00330002,2012-11-06,221,-6.254150,53.350376,225,1171,1,245.94,2012-11-06 08:44:29,Tuesday,559
219457,1352191490,00330002,2012-11-06,221,-6.254206,53.350449,247,1171,0,254.88,2012-11-06 08:44:50,Tuesday,580
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8074067,1352714027,00330002,2012-11-12,221,-6.100567,53.571720,-517,3793,0,33383.58,2012-11-12 09:53:47,Monday,4778
8074522,1352714047,00330002,2012-11-12,221,-6.101975,53.573009,-517,3793,0,33554.70,2012-11-12 09:54:07,Monday,4798
8075897,1352714094,00330002,2012-11-12,221,-6.105751,53.577549,-517,3795,0,34118.51,2012-11-12 09:54:54,Monday,4845
8076491,1352714115,00330002,2012-11-12,221,-6.106295,53.578709,-517,3795,0,34252.55,2012-11-12 09:55:15,Monday,4866
8077034,1352714136,00330002,2012-11-12,221,-6.106322,53.578770,-499,3797,1,34259.57,2012-11-12 09:55:36,Monday,4887
8078139,1352714174,00330002,2012-11-12,221,-6.107205,53.580647,-481,3798,0,34476.51,2012-11-12 09:56:14,Monday,4925
8078671,1352714195,00330002,2012-11-12,221,-6.109101,53.580341,-481,3798,0,34606.62,2012-11-12 09:56:35,Monday,4946
8079170,1352714213,00330002,2012-11-12,221,-6.110092,53.579834,-464,3798,0,34693.18,2012-11-12 09:56:53,Monday,4964
8079746,1352714234,00330002,2012-11-12,221,-6.111845,53.577923,-464,3799,0,34935.50,2012-11-12 09:57:14,Monday,4985
8080287,1352714256,00330002,2012-11-12,221,-6.113324,53.576374,-464,6076,0,35133.79,2012-11-12 09:57:36,Monday,5007
8080844,1352714275,00330002,2012-11-12,221,-6.114451,53.575790,-464,6076,0,35232.77,2012-11-12 09:57:55,Monday,5026
8081436,1352714295,00330002,2012-11-12,221,-6.117560,53.575851,-464,6076,0,35438.82,2012-11-12 09:58:15,Monday,5046
8081942,1352714316,00330002,2012-11-12,221,-6.121200,53.576534,-464,6077,0,35691.63,2012-11-12 09:58:36,Monday,5067
8082484,1352714334,00330002,2012-11-12,221,-6.121528,53.576630,-464,3569,0,35715.84,2012-11-12 09:58:54,Monday,5085
8083072,1352714355,00330002,2012-11-12,221,-6.124474,53.577774,-464,3569,0,35948.84,2012-11-12 09:59:15,Monday,5106
8083539,1352714375,00330002,2012-11-12,221,-6.128592,53.579414,-464,3571,0,36277.04,2012-11-12 09:59:35,Monday,5126
8084121,1352714394,00330002,2012-11-12,221,-6.128348,53.580215,-464,3571,0,36367.64,2012-11-12 09:59:54,Monday,5145
8085168,1352714435,00330002,2012-11-12,221,-6.128348,53.580215,-464,3571,0,36367.64,2012-11-12 10:00:35,Monday,5186
8086074,1352714466,00330002,2012-11-12,221,-6.127436,53.580578,-395,3801,1,36440.31,2012-11-12 10:01:06,Monday,5217
8086343,1352714474,00330002,2012-11-12,221,-6.127436,53.580578,-395,3801,1,36440.31,2012-11-12 10:01:14,Monday,5225
8086891,1352714494,00330002,2012-11-12,221,-6.124733,53.582268,-395,3801,1,36699.98,2012-11-12 10:01:34,Monday,5245
8087391,1352714513,00330002,2012-11-12,221,-6.125583,53.581665,-395,3801,1,36787.58,2012-11-12 10:01:53,Monday,5264
8087978,1352714534,00330002,2012-11-12,221,-6.128633,53.580116,-395,3801,1,37053.15,2012-11-12 10:02:14,Monday,5285
8088545,1352714556,00330002,2012-11-12,221,-6.128733,53.579468,-395,3801,1,37125.57,2012-11-12 10:02:36,Monday,5307
8089036,1352714573,00330002,2012-11-12,221,-6.125267,53.578182,-395,3801,1,37396.11,2012-11-12 10:02:53,Monday,5324
8089601,1352714593,00330002,2012-11-12,221,-6.121233,53.576550,-395,3801,1,37719.21,2012-11-12 10:03:13,Monday,5344
8090714,1352714634,00330002,2012-11-12,221,-6.114267,53.575748,-395,3801,1,38189.19,2012-11-12 10:03:54,Monday,5385
8091786,1352714676,00330002,2012-11-12,221,-6.116133,53.573799,-395,3801,1,38438.85,2012-11-12 10:04:36,Monday,5427
8092350,1352714694,00330002,2012-11-12,221,-6.117116,53.575832,-395,3801,1,38674.30,2012-11-12 10:04:54,Monday,5445
8092937,1352714715,00330002,2012-11-12,221,-6.118700,53.574299,-395,3801,1,38874.60,2012-11-12 10:05:15,Monday,5466

In [77]:
#Check the feature of the new data frame 
df_most[categorical_columns].describe().T

                   count unique       top  freq
Line_ID             2784      2        33  2503
Journey_Pattern_ID  2784      2  00330002  2777
Vehicle_Journey_ID  2784      1       221  2784
Stop_ID             2784    145      3801   415
At_Stop             2784      2         0  2474
day_of_week         2784      5    Friday   868

In [81]:
# Choose one trip and check if the distance feature is right
df_most_Friday=df_most.loc[df['day_of_week']=='Friday']

In [82]:
#Check the feature of the new data frame 
df_most_Friday[categorical_columns].describe().T

                   count unique       top freq
Line_ID              868      2        33  803
Journey_Pattern_ID   868      2  00330002  867
Vehicle_Journey_ID   868      1       221  868
Stop_ID              868     84      3801  407
At_Stop              868      2         0  816
day_of_week          868      1    Friday  868

In [79]:
df_most_Friday

,Timestamp,Line_ID,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Congestion,Lon_WGS84,Lat_WGS84,Delay,Block_ID,Vehicle_ID,Stop_ID,At_Stop,Distance_Terminal,datetime,day_of_week
4690704,1352450087000000,33,00331001,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:34:47,Friday
4691454,1352450108000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:35:08,Friday
4692111,1352450128000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:35:28,Friday
4692762,1352450147000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:35:47,Friday
4693478,1352450170000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:36:10,Friday
4694172,1352450188000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:36:28,Friday
4694863,1352450209000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:36:49,Friday
4695425,1352450227000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:37:07,Friday
4696197,1352450248000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:37:28,Friday
4696898,1352450270000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:37:50,Friday
4697602,1352450289000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:38:09,Friday
4698298,1352450309000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:38:29,Friday
4698937,1352450328000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:38:48,Friday
4699622,1352450348000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:39:08,Friday
4700332,1352450369000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:39:29,Friday
4701129,1352450391000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,0,33002,43055,292,1,0.00,2012-11-09 08:39:51,Friday
4701715,1352450408000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,6,33002,43055,292,1,0.00,2012-11-09 08:40:08,Friday
4702393,1352450428000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,26,33002,43055,292,1,0.00,2012-11-09 08:40:28,Friday
4703155,1352450455000000,33,00330002,2012-11-09,221,0,-6.255217,53.349018,46,33002,43055,292,1,0.00,2012-11-09 08:40:55,Friday
4703844,1352450469000000,33,00330002,2012-11-09,221,0,-6.255105,53.349136,64,33002,43055,292,0,15.10,2012-11-09 08:41:09,Friday
4704442,1352450489000000,33,00330002,2012-11-09,221,0,-6.254168,53.350399,48,33002,43055,1171,0,168.89,2012-11-09 08:41:29,Friday
4705085,1352450508000000,33,00330002,2012-11-09,221,0,-6.255262,53.351917,31,33002,43055,1172,0,352.87,2012-11-09 08:41:48,Friday
4705825,1352450528000000,33,00330002,2012-11-09,221,0,-6.255909,53.352829,31,33002,43055,1172,0,463.13,2012-11-09 08:42:08,Friday
4706543,1352450549000000,33,00330002,2012-11-09,221,0,-6.255909,53.352829,50,33002,43055,1172,0,463.13,2012-11-09 08:42:29,Friday
4707195,1352450569000000,33,00330002,2012-11-09,221,0,-6.256350,53.353443,50,33002,43055,1172,0,537.51,2012-11-09 08:42:49,Friday
4707798,1352450590000000,33,00330002,2012-11-09,221,0,-6.256622,53.353806,67,33002,43055,1173,1,581.78,2012-11-09 08:43:10,Friday
4708484,1352450609000000,33,00330002,2012-11-09,221,0,-6.256760,53.353985,83,33002,43055,1173,0,603.72,2012-11-09 08:43:29,Friday
4709144,1352450627000000,33,00330002,2012-11-09,221,0,-6.257588,53.355190,83,33002,43055,1173,0,748.72,2012-11-09 08:43:47,Friday
4709849,1352450648000000,33,00330002,2012-11-09,221,0,-6.257922,53.355629,83,33002,43055,1173,0,802.40,2012-11-09 08:44:08,Friday
4710562,1352450668000000,33,00330002,2012-11-09,221,0,-6.258642,53.356350,83,33002,43055,1174,1,895.87,2012-11-09 08:44:28,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5239874,1352471674000000,33,00330002,2012-11-09,221,0,-6.119017,53.574249,-348,33002,43055,3801,0,98148.39,2012-11-09 14:34:34,Friday
5240340,1352471697000000,33,00330002,2012-11-09,221,0,-6.119017,53.574249,-348,33002,43055,3801,0,98148.39,2012-11-09 14:34:57,Friday
5240855,1352471715000000,33,00330002,2012-11-09,221,0,-6.119000,53.574249,-348,33002,43055,3801,0,98149.52,2012-11-09 14:35:15,Friday
5241290,1352471734000000,33,00330002,2012-11-09,221,0,-6.119000,53.574268,-348,33002,43055,3801,0,98151.63,2012-11-09 14:35:34,Friday
5241735,1352471756000000,33,00330002,2012-11-09,221,0,-6.119000,53.574268,-348,33002,43055,3801,0,98151.63,2012-11-09 14:35:56,Friday
5242241,1352471775000000,33,00330002,2012-11-09,221,0,-6.119000,53.574268,-348,33002,43055,3801,0,98151.63,2012-11-09 14:36:15,Friday
5242689,1352471793000000,33,00330002,2012-11-09,221,0,-6.118983,53.574268,-348,33002,43055,3801,0,98152.76,2012-11-09 14:36:33,Friday
5243188,1352471816000000,33,00330002,2012-11-09,221,0,-6.118983,53.574268,-348,33002,43055,3801,0,98152.76,2012-11-09 14:36:56,Friday
5243686,1352471836000000,33,00330002,2012-11-09,221,0,-6.118983,53.574268,-348,33002,43055,3801,0,98152.76,2012-11-09 14:37:16,Friday
5244124,1352471854000000,33,00330002,2012-11-09,221,0,-6.118983,53.574268,-348,33002,43055,3801,0,98152.76,2012-11-09 14:37:34,Friday
5244551,1352471875000000,33,00330002,2012-11-09,221,0,-6.118983,53.574268,-348,33002,43055,3801,0,98152.76,2012-11-09 14:37:55,Friday
5245062,1352471895000000,33,00330002,2012-11-09,221,0,-6.126626,53.580944,-348,33002,43055,3801,0,99051.86,2012-11-09 14:38:15,Friday
5245538,1352471914000000,33,00330002,2012-11-09,221,0,-6.118983,53.574268,-348,33002,43055,3801,0,99950.96,2012-11-09 14:38:34,Friday
5246010,1352471934000000,33,00330002,2012-11-09,221,0,-6.118983,53.574284,-348,33002,43055,3801,0,99952.74,2012-11-09 14:38:54,Friday
5246513,1352471955000000,33,00330002,2012-11-09,221,0,-6.126626,53.580944,-348,33002,43055,3801,0,100850.36,2012-11-09 14:39:15,Friday
5246981,1352471973000000,33,00330002,2012-11-09,221,0,-6.118983,53.574268,-348,33002,43055,3801,0,101749.46,2012-11-09 14:39:33,Friday
5247412,1352471994000000,33,00330002,2012-11-09,221,0,-6.118983,53.574268,-348,33002,43055,3801,0,101749.46,2012-11-09 14:39:54,Friday
5247863,1352472014000000,33,00330002,2012-11-09,221,0,-6.118983,53.574268,-348,33002,43055,3801,0,101749.46,2012-11-09 14:40:14,Friday
5248399,1352472036000000,33,00330002,2012-11-09,221,0,-6.118983,53.574268,-348,33002,43055,3801,0,101749.46,2012-11-09 14:40:36,Friday
5248888,1352472055000000,33,00330002,2012-11-09,221,0,-6.119000,53.574249,-348,33002,43055,3801,0,101751.86,2012-11-09 14:40:55,Friday
5249390,1352472075000000,33,00330002,2012-11-09,221,0,-6.119017,53.574249,-348,33002,43055,3801,0,101752.99,2012-11-09 14:41:15,Friday
5249831,1352472096000000,33,00330002,2012-11-09,221,0,-6.119017,53.574268,-348,33002,43055,3801,0,101755.10,2012-11-09 14:41:36,Friday
5250323,1352472116000000,33,00330002,2012-11-09,221,0,-6.119000,53.574268,-348,33002,43055,3801,0,101756.23,2012-11-09 14:41:56,Friday
5250820,1352472134000000,33,00330002,2012-11-09,221,0,-6.119000,53.574268,-348,33002,43055,3801,0,101756.23,2012-11-09 14:42:14,Friday
5251237,1352472155000000,33,00330002,2012-11-09,221,0,-6.118983,53.574268,-348,33002,43055,3801,0,101757.36,2012-11-09 14:42:35,Friday
5251724,1352472175000000,33,00330002,2012-11-09,221,0,-6.118983,53.574284,-348,33002,43055,3801,0,101759.14,2012-11-09 14:42:55,Friday
5252189,1352472194000000,33,00330002,2012-11-09,221,0,-6.118983,53.574284,-348,33002,43055,3801,0,101759.14,2012-11-09 14:43:14,Friday
5262266,1352472622000000,33,00330002,2012-11-09,221,0,-6.118983,53.574284,-348,33002,43055,3801,0,101759.14,2012-11-09 14:50:22,Friday
5272294,1352473043000000,33,00330002,2012-11-09,221,0,-6.118983,53.574284,-348,33002,43055,3801,0,101759.14,2012-11-09 14:57:23,Friday
5288595,1352473724000000,33,00330002,2012-11-09,221,0,-6.118983,53.574284,-348,33002,43055,3801,0,101759.14,2012-11-09 15:08:44,Friday

# Check the Vehicle_Journey_ID which have two Journey_Pattern_ID	 at the same day

In [27]:
# Choose data which the Vehicle_Journey_ID is 6187
df_6187=df.loc[df.Vehicle_Journey_ID==6187]

In [28]:
df_6187[categorical_columns].describe().T

                   count unique       top  freq
Line_ID             1823      1        27  1823
Journey_Pattern_ID  1823      2  00270001  1819
Vehicle_Journey_ID  1823      1      6187  1823
Stop_ID             1823    153      2334    66
At_Stop             1823      2         0  1422
day_of_week         1823      5   Tuesday   398

In [29]:
df_6187_Mon=df_6187.loc[df['day_of_week']=='Monday']

In [30]:
df_6187_Mon[categorical_columns].describe().T

                   count unique       top freq
Line_ID              338      1        27  338
Journey_Pattern_ID   338      2  00270001  337
Vehicle_Journey_ID   338      1      6187  338
Stop_ID              338     89      4595   20
At_Stop              338      2         0  257
day_of_week          338      1    Monday  338

In [31]:
df_6187_Mon

,Timestamp,Line_ID,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Congestion,Lon_WGS84,Lat_WGS84,Delay,Block_ID,Vehicle_ID,Stop_ID,At_Stop,Distance_Terminal,datetime,day_of_week
8532101,1352733287,27,00271001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:14:47,Monday
8532590,1352733307,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:15:07,Monday
8533045,1352733328,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:15:28,Monday
8533524,1352733346,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:15:46,Monday
8533994,1352733367,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:16:07,Monday
8534492,1352733389,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:16:29,Monday
8534970,1352733406,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:16:46,Monday
8535918,1352733449,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:17:29,Monday
8536411,1352733467,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:17:47,Monday
8536815,1352733488,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:18:08,Monday
8537263,1352733506,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:18:26,Monday
8537854,1352733527,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:18:47,Monday
8538281,1352733547,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:19:07,Monday
8538779,1352733566,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:19:26,Monday
8539095,1352733586,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.00,2012-11-12 15:19:46,Monday
8539679,1352733607,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,4,27006,33252,4595,1,0.00,2012-11-12 15:20:07,Monday
8540209,1352733628,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,24,27006,33252,4595,1,0.00,2012-11-12 15:20:28,Monday
8540551,1352733646,27,00270001,2012-11-12,6187,0,-6.172567,53.402115,44,27006,33252,4595,1,0.00,2012-11-12 15:20:46,Monday
8541087,1352733666,27,00270001,2012-11-12,6187,0,-6.173216,53.402145,61,27006,33252,4595,0,43.30,2012-11-12 15:21:06,Monday
8541532,1352733687,27,00270001,2012-11-12,6187,0,-6.178545,53.402561,-27,27006,33252,4596,0,400.75,2012-11-12 15:21:27,Monday
8542516,1352733726,27,00270001,2012-11-12,6187,0,-6.181091,53.401699,-55,27006,33252,4563,1,595.38,2012-11-12 15:22:06,Monday
8543009,1352733747,27,00270001,2012-11-12,6187,0,-6.173216,53.402145,141,27006,33252,4595,0,1121.51,2012-11-12 15:22:27,Monday
8543406,1352733767,27,00270001,2012-11-12,6187,0,-6.181848,53.401230,-28,27006,33252,4563,0,1704.61,2012-11-12 15:22:47,Monday
8543912,1352733788,27,00270001,2012-11-12,6187,0,-6.182587,53.400791,-28,27006,33252,4563,0,1773.91,2012-11-12 15:23:08,Monday
8544420,1352733806,27,00270001,2012-11-12,6187,0,-6.184258,53.399723,-28,27006,33252,1218,1,1936.64,2012-11-12 15:23:26,Monday
8544870,1352733827,27,00270001,2012-11-12,6187,0,-6.184386,53.399620,-11,27006,33252,1218,0,1950.92,2012-11-12 15:23:47,Monday
8545300,1352733845,27,00270001,2012-11-12,6187,0,-6.186112,53.397884,-32,27006,33252,1218,0,2175.66,2012-11-12 15:24:05,Monday
8545796,1352733868,27,00270001,2012-11-12,6187,0,-6.186112,53.397884,-32,27006,33252,1218,0,2175.66,2012-11-12 15:24:28,Monday
8546276,1352733888,27,00270001,2012-11-12,6187,0,-6.187815,53.397800,-32,27006,33252,1218,0,2289.33,2012-11-12 15:24:48,Monday
8546734,1352733907,27,00270001,2012-11-12,6187,0,-6.189254,53.398052,-32,27006,33252,1218,0,2389.07,2012-11-12 15:25:07,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8729218,1352740532,27,00270001,2012-11-12,6187,0,-6.384534,53.283260,210,27006,33488,2351,1,26608.71,2012-11-12 17:15:32,Monday
8729862,1352740554,27,00270001,2012-11-12,6187,0,-6.385767,53.282791,210,27006,33488,2351,0,26706.11,2012-11-12 17:15:54,Monday
8730469,1352740573,27,00270001,2012-11-12,6187,0,-6.387759,53.281651,210,27006,33488,2351,0,26889.82,2012-11-12 17:16:13,Monday
8731163,1352740593,27,00270001,2012-11-12,6187,0,-6.387812,53.281620,234,27006,33488,2351,0,26894.76,2012-11-12 17:16:33,Monday
8731743,1352740612,27,00270001,2012-11-12,6187,0,-6.388171,53.281410,250,27006,33488,2351,0,26928.22,2012-11-12 17:16:52,Monday
8732422,1352740632,27,00270001,2012-11-12,6187,0,-6.389531,53.282196,250,27006,33488,2621,1,27054.24,2012-11-12 17:17:12,Monday
8733175,1352740655,27,00270001,2012-11-12,6187,0,-6.389565,53.282215,274,27006,33488,2621,0,27057.34,2012-11-12 17:17:35,Monday
8733668,1352740672,27,00270001,2012-11-12,6187,0,-6.391389,53.283245,274,27006,33488,2621,0,27224.49,2012-11-12 17:17:52,Monday
8734355,1352740692,27,00270001,2012-11-12,6187,0,-6.392497,53.283936,274,27006,33488,2622,1,27331.14,2012-11-12 17:18:12,Monday
8735028,1352740713,27,00270001,2012-11-12,6187,0,-6.392964,53.284237,294,27006,33488,2622,0,27376.88,2012-11-12 17:18:33,Monday
8735633,1352740731,27,00270001,2012-11-12,6187,0,-6.394654,53.285374,294,27006,33488,2622,0,27546.34,2012-11-12 17:18:51,Monday
8736309,1352740754,27,00270001,2012-11-12,6187,0,-6.395237,53.285789,294,27006,33488,2623,0,27606.71,2012-11-12 17:19:14,Monday
8737029,1352740772,27,00270001,2012-11-12,6187,0,-6.397452,53.287277,294,27006,33488,2623,0,27828.62,2012-11-12 17:19:32,Monday
8737581,1352740791,27,00270001,2012-11-12,6187,0,-6.399758,53.288586,294,27006,33488,2623,0,28040.45,2012-11-12 17:19:51,Monday
8738306,1352740814,27,00270001,2012-11-12,6187,0,-6.400354,53.288891,294,27006,33488,2624,0,28092.72,2012-11-12 17:20:14,Monday
8738991,1352740833,27,00270001,2012-11-12,6187,0,-6.402336,53.289566,294,27006,33488,2624,0,28244.75,2012-11-12 17:20:33,Monday
8741584,1352740912,27,00270001,2012-11-12,6187,0,-6.407082,53.286266,319,27006,33488,4441,0,28729.58,2012-11-12 17:21:52,Monday
8742213,1352740931,27,00270001,2012-11-12,6187,0,-6.407354,53.285946,334,27006,33488,2626,1,28769.55,2012-11-12 17:22:11,Monday
8742952,1352740952,27,00270001,2012-11-12,6187,0,-6.407496,53.285782,351,27006,33488,2626,0,28790.11,2012-11-12 17:22:32,Monday
8743537,1352740973,27,00270001,2012-11-12,6187,0,-6.406656,53.285133,351,27006,33488,2626,0,28881.52,2012-11-12 17:22:53,Monday
8744215,1352740993,27,00270001,2012-11-12,6187,0,-6.406250,53.284981,374,27006,33488,2669,1,28913.45,2012-11-12 17:23:13,Monday
8744923,1352741014,27,00270001,2012-11-12,6187,0,-6.403959,53.284134,374,27006,33488,2669,0,29092.99,2012-11-12 17:23:34,Monday
8745517,1352741032,27,00270001,2012-11-12,6187,0,-6.402215,53.283596,374,27006,33488,2669,0,29223.81,2012-11-12 17:23:52,Monday
8746199,1352741053,27,00270001,2012-11-12,6187,0,-6.401866,53.282906,374,27006,33488,2669,0,29304.05,2012-11-12 17:24:13,Monday
8747502,1352741092,27,00270001,2012-11-12,6187,0,-6.401922,53.282814,419,27006,33488,4641,0,29314.95,2012-11-12 17:24:52,Monday
8748131,1352741111,27,00270001,2012-11-12,6187,0,-6.403017,53.281406,419,27006,33488,4641,0,29487.83,2012-11-12 17:25:11,Monday
8748730,1352741133,27,00270001,2012-11-12,6187,0,-6.403479,53.280899,419,27006,33488,4642,1,29552.12,2012-11-12 17:25:33,Monday
8749454,1352741152,27,00270001,2012-11-12,6187,0,-6.404068,53.279980,435,27006,33488,4642,0,29661.68,2012-11-12 17:25:52,Monday
8750128,1352741172,27,00270001,2012-11-12,6187,0,-6.403242,53.279400,435,27006,33488,4642,0,29746.55,2012-11-12 17:26:12,Monday
8751423,1352741212,27,00270001,2012-11-12,6187,0,-6.403242,53.279400,435,27006,33488,4642,0,29746.55,2012-11-12 17:26:52,Monday

In [87]:
df_6187_Mon_46A=df_6187_Mon.loc[df_6187_Mon['Journey_Pattern_ID']=='00271001']
df_6187_Mon_46A

,Timestamp,Line_ID,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Congestion,Lon_WGS84,Lat_WGS84,Delay,Block_ID,Vehicle_ID,Stop_ID,At_Stop,Distance_Terminal,datetime,day_of_week
8532101,1352733287000000,27,00271001,2012-11-12,6187,0,-6.172567,53.402115,0,27006,33252,4595,1,0.0,2012-11-12 15:14:47,Monday

# Check data for Step 2 new features

In [23]:
df_max_time_Journery=df.loc[(df['Vehicle_Journey_ID']==3977) & (df['day_of_week']=='Friday')]
df_max_time_Journery

,Timestamp,Line_ID,Journey_Pattern_ID,Date,Vehicle_Journey_ID,Congestion,Lon_WGS84,Lat_WGS84,Delay,Block_ID,Vehicle_ID,Stop_ID,At_Stop,Distance_Terminal,datetime,day_of_week
4518807,1352443429,65,065B0001,2012-11-09,3977,0,-6.427217,53.290817,0,65001,33484,4713,0,0.00,2012-11-09 06:43:49,Friday
5920694,1352499885,65,065B1001,2012-11-09,3977,0,-6.233233,53.342300,0,65001,33484,5189,1,0.00,2012-11-09 22:24:45,Friday
5920892,1352499906,65,065B0001,2012-11-09,3977,0,-6.233233,53.342300,0,65001,33484,5189,1,14140.88,2012-11-09 22:25:06,Friday
5921161,1352499924,65,065B0001,2012-11-09,3977,0,-6.233233,53.342300,0,65001,33484,5189,1,14140.88,2012-11-09 22:25:24,Friday
5921474,1352499945,65,065B0001,2012-11-09,3977,0,-6.233233,53.342300,0,65001,33484,5189,1,14140.88,2012-11-09 22:25:45,Friday
5921740,1352499967,65,065B0001,2012-11-09,3977,0,-6.233233,53.342300,0,65001,33484,5189,1,14140.88,2012-11-09 22:26:07,Friday
5921945,1352499985,65,065B0001,2012-11-09,3977,0,-6.233233,53.342300,0,65001,33484,5189,1,14140.88,2012-11-09 22:26:25,Friday
5922211,1352500006,65,065B0001,2012-11-09,3977,0,-6.233233,53.342300,0,65001,33484,5189,1,14140.88,2012-11-09 22:26:46,Friday
5922733,1352500044,65,065B0001,2012-11-09,3977,0,-6.233450,53.342083,0,65001,33484,5189,1,14169.03,2012-11-09 22:27:24,Friday
5923019,1352500065,65,065B0001,2012-11-09,3977,0,-6.233267,53.342285,0,65001,33484,5189,1,14194.60,2012-11-09 22:27:45,Friday
5923271,1352500085,65,065B0001,2012-11-09,3977,0,-6.235683,53.342068,0,65001,33484,5189,1,14357.32,2012-11-09 22:28:05,Friday
5923466,1352500104,65,065B0001,2012-11-09,3977,0,-6.235683,53.342068,0,65001,33484,5189,1,14357.32,2012-11-09 22:28:24,Friday
5923740,1352500126,65,065B0001,2012-11-09,3977,0,-6.240267,53.342602,0,65001,33484,5189,1,14668.37,2012-11-09 22:28:46,Friday
5924037,1352500145,65,065B0001,2012-11-09,3977,0,-6.243166,53.342983,0,65001,33484,5189,1,14866.06,2012-11-09 22:29:05,Friday
5924273,1352500165,65,065B0001,2012-11-09,3977,0,-6.244267,53.343102,0,65001,33484,5189,1,14940.58,2012-11-09 22:29:25,Friday
5924570,1352500185,65,065B0001,2012-11-09,3977,0,-6.244400,53.343151,0,65001,33484,5189,1,14950.98,2012-11-09 22:29:45,Friday
5924833,1352500204,65,065B0001,2012-11-09,3977,0,-6.246316,53.343517,0,65001,33484,5189,1,15084.94,2012-11-09 22:30:04,Friday
5925056,1352500226,65,065B0001,2012-11-09,3977,0,-6.250083,53.344265,0,65001,33484,5189,1,15349.28,2012-11-09 22:30:26,Friday
5925344,1352500244,65,065B0001,2012-11-09,3977,0,-6.254384,53.345116,0,65001,33484,5189,1,15650.98,2012-11-09 22:30:44,Friday
5925633,1352500265,65,065B0001,2012-11-09,3977,0,-6.255084,53.345516,0,65001,33484,5189,1,15715.44,2012-11-09 22:31:05,Friday
5925848,1352500285,65,065B0001,2012-11-09,3977,0,-6.255100,53.346535,0,65001,33484,5189,1,15828.85,2012-11-09 22:31:25,Friday
5926177,1352500305,65,065B0001,2012-11-09,3977,0,-6.256800,53.346832,0,65001,33484,5189,1,15946.79,2012-11-09 22:31:45,Friday
5927504,1352500405,65,065B0001,2012-11-09,3977,0,-6.256074,53.345905,192,65001,33484,5189,0,16060.73,2012-11-09 22:33:25,Friday
5927769,1352500426,65,065B0001,2012-11-09,3977,0,-6.257092,53.346424,221,65001,33484,5189,0,16149.80,2012-11-09 22:33:46,Friday
5928016,1352500446,65,065B0001,2012-11-09,3977,0,-6.254388,53.345867,221,65001,33484,5189,0,16340.25,2012-11-09 22:34:06,Friday
5928244,1352500467,65,065B0001,2012-11-09,3977,0,-6.256591,53.345573,221,65001,33484,5189,0,16490.57,2012-11-09 22:34:27,Friday
5928524,1352500485,65,065B0001,2012-11-09,3977,0,-6.258301,53.345379,221,65001,33484,5189,0,16606.48,2012-11-09 22:34:45,Friday
5928724,1352500505,65,065B0001,2012-11-09,3977,0,-6.258706,53.345173,241,65001,33484,5189,0,16641.88,2012-11-09 22:35:05,Friday
5929067,1352500526,65,065B0001,2012-11-09,3977,0,-6.259223,53.344810,257,65001,33484,5189,0,16694.96,2012-11-09 22:35:26,Friday
5929315,1352500544,65,065B0001,2012-11-09,3977,0,-6.260201,53.344318,257,65001,33484,5189,0,16780.05,2012-11-09 22:35:44,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5958879,1352502847,65,065B0001,2012-11-09,3977,0,-6.380641,53.273434,109,65001,33484,2560,0,31193.15,2012-11-09 23:14:07,Friday
5959139,1352502865,65,065B0001,2012-11-09,3977,0,-6.383101,53.272800,109,65001,33484,2560,0,31371.79,2012-11-09 23:14:25,Friday
5959426,1352502886,65,065B0001,2012-11-09,3977,0,-6.384423,53.272808,109,65001,33484,2561,1,31459.99,2012-11-09 23:14:46,Friday
5959653,1352502906,65,065B0001,2012-11-09,3977,0,-6.386728,53.273083,91,65001,33484,2561,0,31616.78,2012-11-09 23:15:06,Friday
5959854,1352502924,65,065B0001,2012-11-09,3977,0,-6.389527,53.273529,75,65001,33484,2562,0,31809.99,2012-11-09 23:15:24,Friday
5960153,1352502947,65,065B0001,2012-11-09,3977,0,-6.391620,53.273830,75,65001,33484,2564,1,31953.58,2012-11-09 23:15:47,Friday
5960423,1352502965,65,065B0001,2012-11-09,3977,0,-6.392890,53.274086,75,65001,33484,2564,0,32042.97,2012-11-09 23:16:05,Friday
5960704,1352502986,65,065B0001,2012-11-09,3977,0,-6.394594,53.275387,58,65001,33484,4927,0,32227.05,2012-11-09 23:16:26,Friday
5960989,1352503008,65,065B0001,2012-11-09,3977,0,-6.394884,53.277081,42,65001,33484,4928,0,32416.57,2012-11-09 23:16:48,Friday
5961246,1352503026,65,065B0001,2012-11-09,3977,0,-6.395690,53.278259,42,65001,33484,4928,0,32558.27,2012-11-09 23:17:06,Friday
5961471,1352503047,65,065B0001,2012-11-09,3977,0,-6.397222,53.277718,42,65001,33484,4928,0,32676.88,2012-11-09 23:17:27,Friday
5961716,1352503065,65,065B0001,2012-11-09,3977,0,-6.399663,53.276093,42,65001,33484,2352,0,32920.23,2012-11-09 23:17:45,Friday
5961930,1352503085,65,065B0001,2012-11-09,3977,0,-6.401999,53.274689,42,65001,33484,2352,0,33140.91,2012-11-09 23:18:05,Friday
5962214,1352503108,65,065B0001,2012-11-09,3977,0,-6.405404,53.274178,42,65001,33484,2352,0,33375.07,2012-11-09 23:18:28,Friday
5962480,1352503124,65,065B0001,2012-11-09,3977,0,-6.409297,53.274471,42,65001,33484,2573,0,33636.81,2012-11-09 23:18:44,Friday
5962721,1352503146,65,065B0001,2012-11-09,3977,0,-6.412915,53.274780,42,65001,33484,2574,0,33880.61,2012-11-09 23:19:06,Friday
5963008,1352503169,65,065B0001,2012-11-09,3977,0,-6.416204,53.275204,42,65001,33484,2574,0,34105.04,2012-11-09 23:19:29,Friday
5963240,1352503185,65,065B0001,2012-11-09,3977,0,-6.417794,53.276478,42,65001,33484,2574,0,34282.11,2012-11-09 23:19:45,Friday
5963484,1352503206,65,065B0001,2012-11-09,3977,0,-6.419985,53.278130,42,65001,33484,2575,0,34516.98,2012-11-09 23:20:06,Friday
5963711,1352503226,65,065B0001,2012-11-09,3977,0,-6.421273,53.279984,42,65001,33484,2575,0,34740.49,2012-11-09 23:20:26,Friday
5963982,1352503247,65,065B0001,2012-11-09,3977,0,-6.421444,53.282043,42,65001,33484,4929,0,34969.92,2012-11-09 23:20:47,Friday
5964217,1352503267,65,065B0001,2012-11-09,3977,0,-6.421493,53.282631,42,65001,33484,7460,1,35035.44,2012-11-09 23:21:07,Friday
5964409,1352503285,65,065B0001,2012-11-09,3977,0,-6.421731,53.284096,59,65001,33484,7460,0,35199.25,2012-11-09 23:21:25,Friday
5964703,1352503306,65,065B0001,2012-11-09,3977,0,-6.421903,53.286064,59,65001,33484,7460,0,35418.57,2012-11-09 23:21:46,Friday
5964941,1352503328,65,065B0001,2012-11-09,3977,0,-6.422364,53.287628,59,65001,33484,7460,0,35595.32,2012-11-09 23:22:08,Friday
5965174,1352503346,65,065B0001,2012-11-09,3977,0,-6.424883,53.288948,59,65001,33484,4930,0,35818.48,2012-11-09 23:22:26,Friday
5965395,1352503365,65,065B0001,2012-11-09,3977,0,-6.426899,53.290413,59,65001,33484,4931,0,36029.80,2012-11-09 23:22:45,Friday
5965863,1352503405,65,065B0001,2012-11-09,3977,0,-6.426899,53.290413,59,65001,33484,4931,0,36029.80,2012-11-09 23:23:25,Friday
5966326,1352503444,65,065B0001,2012-11-09,3977,0,-6.426899,53.290413,59,65001,33484,4931,0,36029.80,2012-11-09 23:24:04,Friday
5966525,1352503464,65,065B0001,2012-11-09,3977,0,-6.426899,53.290413,59,65001,33484,4931,0,36029.80,2012-11-09 23:24:24,Friday

In [24]:
df_max_time_Journery[categorical_columns].describe().T

                   count unique       top freq
Line_ID              173      2        65  138
Journey_Pattern_ID   173      2  065B0001  172
Vehicle_Journey_ID   173      1      3977  173
Stop_ID              173     58      5189   32
At_Stop              173      2         0  137
day_of_week          173      1    Friday  173

In [26]:
pd.unique(df_max_time_Journery.Journey_Pattern_ID)

array(['065B0001', '065B1001'], dtype=object)